### ISSUE TITLE
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by vernesong** [haishanh/yacd#116]
`Failed to load resource: the server responded with a status of 405 (Method Not Allowed)`

`Failed to load http://192.168.188.139:9090/traffic: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yacd.haishan.me' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
app.6cc7f04cc66718dd2c90.js:29 `

`fetch /traffic error TypeError: Failed to fetch`

这个错误从[f867f02](https://github.com/Dreamacro/clash/commit/f867f0254678342113d06e47f8f5951626b37f59)开始出现，如果设置`external-ui`，并从`http://192.168.188.139:9090/ui/#/`访问，则没有问题。

**Comment by Hesey** [comment]
遇到同样的问题，但macOS下是用GET Method正常，Windows下用OPTIONS导致失败

**Comment by haishanh** [comment]
clash 的改动导致这2个 stream API 的 CORS 设置有问题，我这边做不了什么。如果后面 clash 有改动，我再跟进吧。

closing for now
