### ISSUE TITLE
Traffic Diagram Intermittently Stops Working on Safari

### ISSUE THREAD

**Issue by gaorocks** [haishanh/yacd#13]
Traffic Diagram on overview page sometimes stops working on Safari 12.1 (macOS 10.14.4). It simply displays nothing which looks like no data received from clash. It normally recovers after I cleared local storage followed by restarting Safari. BTW, there's no issue with Chrome.

**Comment by haishanh** [comment]
Thanks for reporting (again)

I can reproduce myself, will dig when I have time.

**Comment by haishanh** [comment]
@gaorocks This issue should've been fixed.

**Comment by haishanh** [comment]
Closing
