### ISSUE TITLE
clash-dev 无法显示流量及日志

### ISSUE THREAD

**Issue by asdf12303116** [haishanh/yacd#201]
arch linux 环境下，使用clash最新dev版本，流量一直显示为0.同时日志也无法显示。

curl 测试clash 的 RESTful api正常，流量及日志有有输出

**Comment by haishanh** [comment]
如果你重新编译最新的 clash dev branch，应该就没这个问题了。

clash dev 最新的 commit （https://github.com/Dreamacro/clash/commit/50d2e082d55d8205b1eced3e83976a7d6f541dbc） 添加了 web socket 认证的支持。
