### ISSUE TITLE
建议增加docker镜像支持

### ISSUE THREAD

**Issue by xuanyuanaosheng** [haishanh/yacd#261]

**Comment by haishanh** [comment]
@xuanyuanaosheng 使用场景是什么。只是些静态文件，实在没必要做个 docker image。

**Comment by xuanyuanaosheng** [comment]
方便快速使用，拉下来直接启动就可以，不用在编译了

**Comment by haishanh** [comment]
@xuanyuanaosheng 用这个链接可以直接下载 build 好的 

https://github.com/haishanh/yacd/archive/gh-pages.zip

**Comment by haishanh** [comment]
https://github.com/haishanh/yacd/pull/279 里面添加了一个 Dockerfile，可以用用看。

Closing.

**Comment by lvhe19880210** [comment]
> @xuanyuanaosheng 用这个链接可以直接下载 build 好的
> 
> https://github.com/haishanh/yacd/archive/gh-pages.zip

请问这个连接里的build会一直随clash主程序更新下去吗？

**Comment by haishanh** [comment]
@lvhe19880210 

首先这个项目只是 clash 的前端。clash 的更新和这个项目的更新没有关系。假设 clash 更新后，yacd 上会有不兼容的问题，可以直接开 issue 反馈。

gh-pages.zip 是由最新的 tag build 出来的，只要 tag 更新了，gh-pages 也会更新。

**Comment by lvhe19880210** [comment]
> @lvhe19880210
> 
> 首先这个项目只是 clash 的前端。clash 的更新和这个项目的更新没有关系。假设 clash 更新后，yacd 有不兼容的问题，可以直接开 issue 反馈。
> 
> gh-pages.zip 是由最新的 tag build 出来的，只要有了新 tag，gh-pages 也会更新。

好的 多谢您啦～～
