### ISSUE TITLE
[Feature Request] Close All Connections

### ISSUE THREAD

**Issue by HueLiu** [haishanh/yacd#338]
Hello,

If you could add a button that can close all Connections, that would be nice.

Just like the screenshot at http://clash.razord.top below:
![image](https://user-images.githubusercontent.com/19755727/69873617-c9c97f00-12f3-11ea-85e8-0b674ef3120d.png)

![image](https://user-images.githubusercontent.com/19755727/69873756-23ca4480-12f4-11ea-89ed-98efdb68535d.png)

Thanks :)

**Comment by haishanh** [comment]
@HueLiu It's supported now.

Closing as done.
