### ISSUE TITLE
连接和总流量无法显示

### ISSUE THREAD

**Issue by outloudvi** [haishanh/yacd#390]
其它页面正常，但 `#/connections` 页面无法显示当前存在的连接。这里请求了 RESTful API 的 `/connections` 端点，但 clash 目前似乎[并没有](https://github.com/Dreamacro/clash/blob/d1fb442bd51ca697f8d9f7b3d451c9bdd83401cd/hub/route/server.go#L64-L69)这个 endpoint。

主页的上传总量、下载总量和活动连接数也无法显示。可能亦与 `/connections` 有关。

**Comment by haishanh** [comment]
@outloudvi 你需要 dev branch 的 clash 

https://github.com/Dreamacro/clash/blob/dev/hub/route/server.go#L64-L71

**Comment by outloudvi** [comment]
谢谢 :-)

**Comment by qunsi** [comment]
我看不懂代码，能教教怎么弄才能看到连接数吗？
