### ISSUE TITLE
Entire page crash when Proxy component try to display DIRECT

### ISSUE THREAD

**Issue by comzyh** [haishanh/yacd#4]
Entire page crash when `Proxy` try to display `DIRECT`

https://github.com/haishanh/yacd/blob/2e43f46c7a7d62e0aad47ba339ef8278aa4fd0b4/src/components/Proxy.js#L43-L49

when `name` equals `DIRECT`, obviously  `proxies[name]`  is, undefined,  the `proxy.type` will triger 

> Uncaught TypeError: Cannot read property 'type' of undefined

and let the entire page crash.

Reproduce: 
config.yaml for clash
```
'Proxy Group':
  - { name: 'Apple Service', type: select, proxies: [DIRECT, XXXX] }
```
and `ProxyGroup2` will create the `Proxy` component with name `DIRECT`
https://github.com/haishanh/yacd/blob/2e43f46c7a7d62e0aad47ba339ef8278aa4fd0b4/src/components/ProxyGroup.js#L51

**Comment by haishanh** [comment]
This is great bug reporting. Thanks @comzyh !

**Comment by comzyh** [comment]
Thanks, it works.
