### ISSUE TITLE
登陆不进去

### ISSUE THREAD

**Issue by coldgemini** [haishanh/yacd#414]
一直在同一个页面，要怎么进去？
![yacd](https://user-images.githubusercontent.com/33364009/71334385-ea929680-2578-11ea-8dea-6fa117138aeb.png)

**Comment by haishanh** [comment]
@coldgemini 需要看一下你的 clash 配置文件

```
external-controller: 127.0.0.1:1234
secret: 123
```

`external-controller` 对应上面的 Hostname 和 Port

配置文件中的 `secret` 不是必须的，但如果设置了， UI 上也必须填写。

**Comment by coldgemini** [comment]
en, en

**Comment by Comah** [comment]
一直没问题 你登陆不进去是你自己配置文件的问题吧  这个太好用了 暗黑模式
