### ISSUE TITLE
关于 Test Latency

### ISSUE THREAD

**Issue by Synchronized1** [haishanh/yacd#452]
大佬你好😊
环境是:
  openwrt+open-clash(Fake-IP模式)
我遇到一个问题: 
     在Proxies模块,点击Test Latency 没有出现任何测速结果,请问是需要什么额外的配置吗?

**Comment by haishanh** [comment]
@Synchronized1 不需要什么额外配置，可能是你的节点太多了？ 测速时间会比较长点。

**Comment by LakeishaKowalczyk** [comment]
@haishanh 

+1
OpenClash 里用着用着延迟测试没效果了，刚装上是好的
在两个路由器（硬+软）都这样

Yacd Version 0.3.6
OpenClash v0.45.141-beta
内核版本 [Meta] alpha-g3a9fc39
