### ISSUE TITLE
更新了之后更方便简洁一目明了

### ISSUE THREAD

**Issue by Comah** [haishanh/yacd#468]
ui排版真的越来越好看实用了 之前觉得全部线路不能隐藏很乱 现在能隐藏也能用小圆点显示网络状态 实在太棒了  辛苦了 加油啊 ！设置那里能否加上密码设置呢？secret:

**Comment by Comah** [comment]
> @Comah 谢谢
> 
> secret 没法通过 rest API 修改，目前能修改的有这么几个东西 https://github.com/Dreamacro/clash/blob/dev/hub/route/configs.go#L25-L33

不能修改的话没办法了 只能自己手动添加到规则里面去了。
还有就是 LogLevel 能否默认 silent ? 默认info的话 在路由器的Log不停地刷新一堆log

**Comment by haishanh** [comment]
这个你在 clash 的 config.yaml 中设置就可以了吧

**Comment by Comah** [comment]
> 这个你在 clash 的 config.yaml 中设置就可以了吧

也可以的 但是一般都是用的api一键更更新 如果要改动的话还是需要手动去改 更新完订阅之后手动去改
路由器更新一次要卡很久 更新完之后 然后手动改 按应用之后又要卡很久才能使用。老毛子的固件 估计未完善

**Comment by haishanh** [comment]
大概了解了你的意思，但 UI 主动修改配置对我来说是 anti pattern
