### ISSUE TITLE
如何修改主题

### ISSUE THREAD

**Issue by Tokyonth** [haishanh/yacd#470]
请问怎么把主题修改为默认白色的，，眼拙我在代码中没发现

**Comment by haishanh** [comment]
@Tokyonth 如果你是 fork 后改代码的话，改这里

https://github.com/haishanh/yacd/blob/1229afeb52c2a7f09718f5240adbc5f8895dc18b/src/store/app.js#L88

**Comment by Tokyonth** [comment]
> @Tokyonth如果你是fork后改代码的话，改这里
> 
> https://github.com/haishanh/yacd/blob/1229afeb52c2a7f09718f5240adbc5f8895dc18b/src/store/app.js#L88

如果是打包好的呢，我通过搜索改了app-xxx.js相同的内容，但貌似没有效果

**Comment by haishanh** [comment]
@Tokyonth 主题设置一次 就会保存下来。如果没有切换浏览器并且页面地址没有变的话，设置不会变。

**Comment by Tokyonth** [comment]
> @Tokyonth 主题设置一次 就会保存下来。如果没有切换浏览器并且页面地址没有变的话，设置不会变。

有什么办法不换浏览器和页面让他变过来吗，手机端没有主题切换按钮，后面会做这个吗

**Comment by haishanh** [comment]
暂时不准备在小屏幕上加这样的按钮

现在可以在 url 上通过 querystring 来设置

```
?theme=dark
?theme=light
```

**Comment by RikudouPatrickstar** [comment]
@haishanh 请问下可以在 [index.html](https://github.com/haishanh/yacd/blob/05691cc82913e46a9a6bef3addb106c32702235e/index.html#L19) 中类似 `data-base-url="http://127.0.0.1:9090"`  的方式指定默认语言和主题吗？
