### ISSUE TITLE
https无法使用

### ISSUE THREAD

**Issue by haoxingxing** [haishanh/yacd#472]

**Comment by haoxingxing** [comment]
src/misc/request-helper.js line:14 http=>https
src/api/traffic.js line:79 ws=>wss
src/api/logs.js line:68 ws=>wss
src/api/connections.js line:52 ws=>wss

**Comment by haoxingxing** [comment]
src/misc/request-helper.js line:14 http=>https
src/api/traffic.js line:79 ws=>wss
src/api/logs.js line:68 ws=>wss
src/api/connections.js line:52 ws=>wss

**Comment by haishanh** [comment]
@haoxingxing clash 的 rest API 支持 https 吗？

**Comment by haoxingxing** [comment]
反向代理

**Comment by haishanh** [comment]
Supported in [`v0.2.6`](https://github.com/haishanh/yacd/blob/master/CHANGELOG.md#026-2020-09-08) now.
