### ISSUE TITLE
将clash内核替换成clashR内核之后 SR线路的节点没有ping延迟

### ISSUE THREAD

**Issue by Comah** [haishanh/yacd#474]
同样是替换了内核的clashR 所有的SSR线路在razord上能测速测出Ping延迟 但在yacd上的SSR线路就没有， 但yacd上的SS、V2R线路测速正常。对于一些需要获取ping的规则例如：url-test fallback loadbalance这些都似乎严重依赖于线路的ping而作出优选。

**Comment by ackurdeeve** [comment]
原版cladh core就不支持ssr，你想啥呢……

**Comment by Comah** [comment]
> 原版clash core就不支持ssr的，所以没有的话也别要求太多了

你误会我意思了吧 我已经替换掉内核 是支持的  但是节点页面不显示PING  而razord是能显示ping
我上个图吧：
![TIM图片20200301161729](https://user-images.githubusercontent.com/20982819/75622137-2d579700-5bd8-11ea-8971-4935b4f8141f.png)
![TIM图片20200301161734](https://user-images.githubusercontent.com/20982819/75622139-30528780-5bd8-11ea-95ee-3ba4b9e12f60.png)

**Comment by haishanh** [comment]
@Comah 新版(`0.1.9`)应该可以了

**Comment by Comah** [comment]
> @Comah 新版(`0.1.9`)应该可以了

真的已经可以了 今晚吃完饭更新后看到全部已经能显示ping了   谢谢大佬！辛苦了
