### ISSUE TITLE
怎么开机启动？

### ISSUE THREAD

**Issue by JunShine** [haishanh/yacd#476]
想尝试systemd，但不懂怎么添加命令行。没用过yarn啊

**Comment by haishanh** [comment]
@JunShine 都是静态文件 你下载 https://github.com/haishanh/yacd/archive/gh-pages.zip 解压后 直接用一个 web server host 这些静态文件就行了

**Comment by haishanh** [comment]
可以看一下这个 Dockerfile https://github.com/haishanh/yacd/blob/master/Dockerfile
