### ISSUE TITLE
小白问题：如何指定URL端口？

### ISSUE THREAD

**Issue by caesarjing** [haishanh/yacd#477]
看到0.18版本后可以用`?hostname=`来指定访问的服务地址，请问如何访问定制端口的服务地址？

例：http://yacd.haishan.me/?hostname=192.168.1.1  vs http://yacd.haishan.me/?hostname=127.0.0.1:6891

谢谢！

**Comment by haishanh** [comment]
@caesarjing 大概这样 `http://yacd.haishan.me?hostname=127.0.0.1&port=6991&secret=hello`

**Comment by caesarjing** [comment]
感谢！
