### ISSUE TITLE
close connections while switching proxies

### ISSUE THREAD

**Issue by oott123** [haishanh/yacd#478]
clash-dashboard 最近加入了这个功能： https://github.com/Dreamacro/clash-dashboard/commit/48668b93128ec9f1524f98df1da7bbe31872d4ee

yacd 是否有计划加入呢

**Comment by haishanh** [comment]
@oott123 可以加 看了 clash-dashboard 的代码，但我不明白为什么要这样做

切换到 proxyA 就把当前 proxyA 的链接都断开。意义是什么？

知道的话 麻烦解释一下？

**Comment by oott123** [comment]
应该是和 clash for windows 的[这个](https://docs.cfw.lbyczf.com/contents/breakconn.html)功能配置成 `proxy: chain` 一样，用处就是切换某个 chain 的代理目标的时候，把现有的使用这个 chain 的连接都打断掉。这是为了让这些连接重新建立，以使用这个 chain 的新目标。

**Comment by Synchronized1** [comment]
@haishanh  例如我有这样一种需求,我在使用某个节点用作google drive/onedrive的上传,发现该节点上传被限速,所以我需要切换到其它节点,但是由于上一个节点链接未关闭,导致依然使用上一个节点做上传!

**Comment by haishanh** [comment]
新版本加了类似功能，在切换时会弹框提示 https://github.com/haishanh/yacd/blob/master/CHANGELOG.md#0119-2020-06-07
