### ISSUE TITLE
刷新页面后收起的策略组又回重新展开

### ISSUE THREAD

**Issue by lvhe19880210** [haishanh/yacd#480]
当节点很多时每次刷新都要调整 太麻烦了 我用的是主页提供的静态页面，把yacd-gh-pages文件夹里的dashboard文件放到ui文件夹映射到clash的docker中，不知道是否跟这个静态页面文件夹没更新有关？

**Comment by haishanh** [comment]
@lvhe19880210 跟你说的没有关系。目前折叠状态并不会保存。我会考虑一下要不要做这样的功能。

**Comment by haishanh** [comment]
@lvhe19880210 新版本加了这个功能了

**Comment by lvhe19880210** [comment]
> @lvhe19880210 新版本加了这个功能了
折叠功能很完美了，不管是切换还是刷新页面都能保存，希望hide unavalable proxy这个选项在刷新页面时也能保存。目前这个选项仅在切换tab的时候能保存，不知道技术上难不难，再次谢谢您这么快回复
