### ISSUE TITLE
能否给个选项,不自动排序

### ISSUE THREAD

**Issue by magiclu** [haishanh/yacd#481]
自动排序后,一般香港之类的节点延迟低会在前面,美国的会在后面,但是我的用的机场美国的稳定很多,这样我找起来不方便
默认的,就像windows的客户端一样,每个国家的节点基本在一起,测速后不会排序更适合我

**Comment by haishanh** [comment]
@magiclu 新版本加了排序选项 点击 proxies 页面右上角的按钮后 会有选项

我关 issue 了，有问题再开。
