### ISSUE TITLE
Sorting In Group

### ISSUE THREAD

**Issue by Synchronized1** [haishanh/yacd#483]
白色主题:
![image](https://user-images.githubusercontent.com/58451554/82117728-c8f2af80-97a4-11ea-91ae-70096054e8ed.png)

黑色主题:无法正常显示下拉列表内容
![image](https://user-images.githubusercontent.com/58451554/82117731-d60f9e80-97a4-11ea-9708-ef96ae62eb26.png)

应该是CSS样式的问题..

**Comment by Synchronized1** [comment]
找到了背景色问题:
![image](https://user-images.githubusercontent.com/58451554/82117841-9f865380-97a5-11ea-941a-a785c2d8658c.png)

希望作者有时间可以修复下.

**Comment by haishanh** [comment]
@Synchronized1 修掉了，谢谢提醒。

**Comment by haishanh** [comment]
先关 issue 了
有问题再开
