### ISSUE TITLE
yacd的一些建议

### ISSUE THREAD

**Issue by Synchronized1** [haishanh/yacd#486]
1.从A节点切换B节点会关闭之前使用A节点的所有连接,从而重新使用B节点建立连接
      
```
    场景一:A节点看youtube速度不给力,我想切换B节点观看,由于在不关闭浏览器
       情况下,会导致连接一直占用A节点
      
    场景二:就是上传,A节点上传被限速,切换B节点上传
       GoogleDrive或OneDrive会依然使用A节点,需要暂停重新开始才能切换到B 
```

2.单独ping某个节点与只ping该策略下的所有节点
  ```
功能预想:在每个策略后面加上一个图标,点击后拆分出两个功能:一个是仅ping当前策略中的选中节 
                 点,还有一个是 ping该策略下的所有节点
```
   
 
![image](https://user-images.githubusercontent.com/58451554/83320113-ddd84400-a276-11ea-9a84-c06fbcf95491.png)

`  节点特别多,这个部分ping就非常实用,不用每次ping全部`

3.排序规则精确到每个策略组上

**Comment by haishanh** [comment]
@Synchronized1 谢谢 收到了 会考虑这些建议的

**Comment by haishanh** [comment]
@Synchronized1 前2点都应该做好了，第3点真的有必要吗？

不是做起来有难度，只是觉得在 group 标题后面 "按钮 +1, 好看 -1"，也许有更好的方案，但我还没想到。

**Comment by Synchronized1** [comment]
@haishanh 这个第三点这个组内排序其实可有可无🤣🤣🤣
