### ISSUE TITLE
页面显示问题

### ISSUE THREAD

**Issue by lloyd18** [haishanh/yacd#488]
![Snipaste_2020-05-23_10-42-54](https://user-images.githubusercontent.com/10294460/82720013-3725fd80-9ce2-11ea-893c-d085efb295e6.png)

可以优化一下yacd面板的conns页面显示吗，
每次查看目标IP都要拖动滚动条到右边，
可以看到中间还有较多空白，
如果显示信息做紧凑一点
一屏显示应该问题不大吧

使用环境，windows10，分辨率 1080p，100%缩放

**Comment by haishanh** [comment]
@lloyd18 谢谢

刚刚发了个新的版本，稍微减小了一下整个表的宽度，你可以用用看。

**Comment by lloyd18** [comment]
辛苦了，还得等openclash跟进更新，自己不会修改，这个iss我就关了
