### ISSUE TITLE
希望有修改规则的功能

### ISSUE THREAD

**Issue by ttttmr** [haishanh/yacd#489]
看了有修改config的api

PUT方法，路由是/configs
数据参数有2个
path 文件绝对路径
payload yaml配置

https://github.com/Dreamacro/clash/blob/646bd4eeb4bbea6628987be55a167c45e718f77a/hub/route/configs.go#L80-L83

webui可以用payload参数实现修改规则

**Comment by ttttmr** [comment]
文档上没有payload的说明
https://clash.gitbook.io/doc/restful-api/config
但releases 有说明，从0.17.0开始支持
https://github.com/Dreamacro/clash/releases/tag/v0.17.0

**Comment by ttttmr** [comment]
另外提一个想法，webui是不是也可以做成chrome扩展程序的形式（类似aria2的各种webui的扩展程序），也能快速方便对当前访问的网址添加/修改规则

**Comment by ttttmr** [comment]
#468 提到的修改secret等patch不能改的部分，似乎都可以通过payload参数修改整个config实现更改😂

**Comment by haishanh** [comment]
@ttttmr 我知道有这个 API，这个 API 在桌面端会比较有用，但在 web 上可用性太低

因为目前 Clash 没有 API 可以拿到完整的 config 文件内容以及其文件路径 (包括现有的  `GET /configs`) (桌面端至少还可以直接读文件系统上的 config.yaml)

所以 `PUT /configs` 时没办法 patch 现有的 config。通过 update path 的方式 hot switch config 文件，在 web 端**可能稍微有一些**意义。

**Comment by haishanh** [comment]
力所不能及

(等哪天脑抽了的话 做个 electron 版本，但说实话 electron 的版本 我自己都不愿用，所以...)

closing
