### ISSUE TITLE
是否可以支持log的导出

### ISSUE THREAD

**Issue by xqXQzzz1** [haishanh/yacd#490]

**Comment by haishanh** [comment]
@xqXQzzz1 这个做不了。目前 log 收集是 lazy 的，只有浏览到 log 页面才会开始收集。其次为了减小内存使用，最多只会保留 300 条 log 记录。另外，web 没有特别合适持久化这个 log 的 infra，刷新页面后 log 就没有了。

还是推荐从源头收集 log，运行 clash 之后重定向 stdout，或者调 log rest/websocket API 收集。
