### ISSUE TITLE
模式无法更改，点击模式按钮没有反应

### ISSUE THREAD

**Issue by xy9860** [haishanh/yacd#491]
如图，按钮高亮的部分跑到按钮外面去了，三个模式点击都没有反应。我只是设置了两个provider。
![2f6d84aa8fd25d2b](https://user-images.githubusercontent.com/25838633/83960357-8eb79200-a8ba-11ea-99f9-e17b39620b92.png)
Proxies这边的Global还多了一个不可点击的Global按钮
![-6ed6d0fc476952c8](https://user-images.githubusercontent.com/25838633/83960391-dd652c00-a8ba-11ea-8bb6-6832bded179b.png)

**Comment by xy9860** [comment]
又测了一下，功能是正常的，只是显示不正常

**Comment by haishanh** [comment]
@xy9860 感谢反馈，新版本修了这个问题 https://github.com/haishanh/yacd/blob/master/CHANGELOG.md#0119-2020-06-07
