### ISSUE TITLE
功能请求：保存 Proxy Group 中的 select 的状态

### ISSUE THREAD

**Issue by suiahae** [haishanh/yacd#492]
“当我使用 Dashboard 选择节点时，clash重启后会重新切换会默认节点，希望能保存选择节点后的状态。”

_引用自：https://github.com/Dreamacro/clash-dashboard/issues/11_

**Comment by haishanh** [comment]
@suiahae 引用的 issue 里面 Dreamacro 也解释了。因为当前 clash 本身不会在重启后保持 select 状态，在没法控制 clash executable 的运行和关闭的情况下，浏览器保存 select 状态没有意义。

只有直接运行于操作系统上的客户端，保存 select 状态才会比较有用。
