### ISSUE TITLE
最新版本地页面包 gh-pages 里面好多字体文件，全都是需要的么

### ISSUE THREAD

**Issue by xy9860** [haishanh/yacd#494]
有没有可能删掉精简一些呢，对不起，原谅我这个事儿B吧。。。
还有一点疑问，在GLOBAL的分组下面为什么还有一个GLOBAL，感觉好像没有用处

**Comment by haishanh** [comment]
@xy9860 那些字体文件不是全必须的，大概只用到了三四个左右，我只是偷了下懒 直接用了别人的库 https://github.com/KyleAMathews/typefaces 我回头改善下

GLOBAL 里面还有个 GLOBAL 可能是我的 bug。另外 GLOBAL 应该是 clash 的内部 group，我也在考虑不要将其暴露在 UI 上。

**Comment by haishanh** [comment]
@xy9860 我发了新版本，减小了字体文件个数。同时把 Inter 化成了 Open Sans，字体文件尺寸也会减小些

关于 GLOBAL 的问题
貌似之前是有意把 GLOBAL append 到 GLOBAL group 的最后，我不记得具体原因了，就保留这样把

https://github.com/haishanh/yacd/blob/263a4335eb83d8417f844ea34f21651fe3c062e5/src/store/proxies.tsx#L359-L360
