### ISSUE TITLE
v0.38.8 yacd面板节点排序问题

### ISSUE THREAD

**Issue by btcforver** [haishanh/yacd#496]
大佬好：
更新到最新的版本后，发现节点按延迟排序出现如下情况，不可用的节点跑最前面来了，之前的版本都正常的(延迟最低的绿色节点在最前面)，求指导：
![image](https://user-images.githubusercontent.com/60208053/84152490-4bfee100-aa97-11ea-84af-a7aa6235d734.png)
![image](https://user-images.githubusercontent.com/60208053/84152500-54571c00-aa97-11ea-92bf-5f48d51134b1.png)

**Comment by haishanh** [comment]
![image](https://user-images.githubusercontent.com/1166872/84170844-abb3b700-aaac-11ea-84da-543bfae08b84.png)

@btcforver 先试一下点击上面这个按钮，然后改一下排序看看？

**Comment by btcforver** [comment]
![image](https://user-images.githubusercontent.com/60208053/84214509-2654f480-aaf6-11ea-9bb2-e7e18ad2eefe.png)
我平时都是用的延迟由低到高排序，前面版本节点排序顺序是：低延迟节点（绿色）-->高延迟节点（橙色）-->不可用节点（灰色）
现在更新到新版本，节点排序变成了：不可用节点（灰色）-->低延迟节点（绿色）-->高延迟节点（橙色）如下图：
![image](https://user-images.githubusercontent.com/60208053/84214798-fa863e80-aaf6-11ea-81c9-3ce31decb54a.png)
![image](https://user-images.githubusercontent.com/60208053/84214817-05d96a00-aaf7-11ea-928d-c1f3c327796a.png)
这样会造成一堆没用的节点排在最前面，有没有办法想以前版本那样，让延迟最低的绿色排前面，按照这个顺序来：低延迟节点（绿色）-->高延迟节点（橙色）-->不可用节点（灰色）？

**Comment by haishanh** [comment]
@btcforver 这应该是个 bug，我回头修下

**Comment by btcforver** [comment]
谢谢大佬！！

**Comment by xqXQzzz1** [comment]
> 
> 
> @btcforver 这应该是个 bug，我回头修下

但是现在策略组也会被排在后面
![图片](https://user-images.githubusercontent.com/35725489/84851707-9da5fd80-b08d-11ea-8041-cc7c3ff608e3.png)
十分难受

**Comment by xqXQzzz1** [comment]
> 
> 
> @btcforver 这应该是个 bug，我回头修下

目前一刷新，无效节点还是不能隐藏
![图片](https://user-images.githubusercontent.com/35725489/84853934-e6ac8080-b092-11ea-8031-7d9ceeba7b6d.png)

**Comment by btcforver** [comment]
![image](https://user-images.githubusercontent.com/60208053/84982044-62c4c800-b168-11ea-8764-fbf670d93d06.png)
大佬，今天更新了之后，无效节点直接跑最后去了，但是发现策略组也跑后面去了，排序貌似成了：低延迟有效节点-->高延迟有效节点-->策略组-->不可用节点，能否更新成最早的顺序：策略组-->低延迟有效节点-->高延迟有效节点-->不可用节点
谢谢

**Comment by haishanh** [comment]
@btcforver 改了

隐藏无效节点的功能应该也好了
