### ISSUE TITLE
clash可以使用mix port，是否可以跟进？

### ISSUE THREAD

**Issue by xqXQzzz1** [haishanh/yacd#503]

**Comment by haishanh** [comment]
master 上的代码可以现实 mixed port 了，但还没发版本，可以自己手动 build 或者用 latest 标签的 docker image

如果这几天有空，准备支持一下 rule provider 之后在发个版本

**Comment by xqXQzzz1** [comment]
如何build，是否可以给些教程

**Comment by haishanh** [comment]
暂时没空做 rule provider，我发了新版本


To build:

```sh
# install dependencies
yarn

# build optimized assets ( will be in directory "public")
yarn build
```

**Comment by xqXQzzz1** [comment]
![图片](https://user-images.githubusercontent.com/35725489/86263560-fc25bc80-bbf3-11ea-8f1e-fe8e42c13f96.png)
![图片](https://user-images.githubusercontent.com/35725489/86263605-09db4200-bbf4-11ea-980a-c87928f2f5a3.png)
不能识别？
