### ISSUE TITLE
希望设置里更改全局、规则、直连时可以打断所有连接

### ISSUE THREAD

**Issue by zhouzl7** [haishanh/yacd#505]
希望设置里更改全局、规则、直连时可以打断所有连接

**Comment by zhouzl7** [comment]
目前在Switch到直连模式下，再不重启浏览器的情况下，依旧是可以访问外网的。Switch到全局模式或者规则模式都有类似的情况。

**Comment by haishanh** [comment]
@zhouzl7 切换模式后，可以到 connections 页面 手动关闭一下所有连接吧。（鼠标悬浮右下角的按钮，会出现关闭所有连接的选项)

**Comment by sandianyue** [comment]
附议  个人觉得像dashboard那样提供切换节点自动打断选项很有必要😀

**Comment by haishanh** [comment]
@sandianyue  点击这里 可以打开 自动关闭 old connection 的选项 你看下是不是你要的
![image](https://user-images.githubusercontent.com/1166872/93958459-1d2c2280-fd89-11ea-87e4-62dafeaaed21.png)

**Comment by sandianyue** [comment]
> @sandianyue 点击这里 可以打开 自动关闭 old connection 的选项 你看下是不是你要的
> ![image](https://user-images.githubusercontent.com/1166872/93958459-1d2c2280-fd89-11ea-87e4-62dafeaaed21.png)

啊  是的是的  没有发现还有这个设置入口  里面设置项很强大 居然还有重新sort和隐藏不可用节点  感谢您的工作😀
