### ISSUE TITLE
Connections not loading when secret contains special characters

### ISSUE THREAD

**Issue by JokerQyou** [haishanh/yacd#507]
When accessing connections API yacd simply appends the secret as `token` query parameter. If the secret contains `&` then value received by clash server would never match.

**Comment by JokerQyou** [comment]
I was going to create a new issue in the clash repository but I noticed something strange. This is a minimal sample config file you can use to start a local clash instance for debugging.

<details>
  <summary>config.yaml</summary>

```yaml
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:7893
secret: '123&456!'
#external-ui: public
```
</details>

- Run a local instance with the above config
- Open a new browser tab, open dev tools in advance
- Go to http://yacd.haishan.me/ and login to the local instance
- View "Console" panel and you'll notice all the websocket requests have failed

However if you go to "Network" panel, following the failed request to `ws://127.0.0.1:7893/traffic?token=123&456!` there is an additional successful `GET` request (see screenshot below). This request is sent via `fetch` and have auth headers set properly. It looks like a chunked stream since it never stops, which I think is a fallback used by yacd, correct me if I'm wrong.

![image](https://user-images.githubusercontent.com/1465267/87250040-16358980-c495-11ea-9763-ffe81d90570e.png)

However for the other two websocket APIs (connections and logs) there is no such fallback requests, even if I switch between different pages and do a reload.

Is this something yacd can workaround, or should I report this issue to the upstream (probably just to update their documentation about `secret`)?

**Comment by haishanh** [comment]
Thanks. It's in [v0.2.1](https://github.com/haishanh/yacd/blob/master/CHANGELOG.md#021-2020-07-13) now.
