### ISSUE TITLE
离线版本可以提供记录选择节点的功能吗？

### ISSUE THREAD

**Issue by xqXQzzz1** [haishanh/yacd#509]

**Comment by haishanh** [comment]
@xqXQzzz1 做不到， clash 不会在重启之间保持节点选择状态。 而网页客户端 和 clash 的生命周期又是完全独立的，网页端记录状态，也没法第一时间传递给 clash。

**Comment by flyhigherpi** [comment]
> @xqXQzzz1 做不到， clash 不会在重启之间保持节点选择状态。 而网页客户端 和 clash 的生命周期又是完全独立的，网页端就算记录了状态也没法第一时间传递给 clash。

大大，那cfw.跟cfa的记忆机制是怎么处理的。路由器我现在只能变通，将指定节点置前

**Comment by haishanh** [comment]
@flyhigherpi cfw 和 cfa 是直接跑在系统上的 application，它们可以在启动的时候 直接也启动 clash，但是 web 做不到

**Comment by xqXQzzz1** [comment]
> 
> 
> > @xqXQzzz1 做不到， clash 不会在重启之间保持节点选择状态。 而网页客户端 和 clash 的生命周期又是完全独立的，网页端就算记录了状态也没法第一时间传递给 clash。
> 
> 大大，那cfw.跟cfa的记忆机制是怎么处理的。路由器我现在只能变通，将指定节点置前

流程上，在关闭clash的命令之前，执行 get /proxies，得到节点信息，然后解析json文件，找到select类型的，保存now，记录到一个文件里，再次打开的时候，根据文件 put /proxies

**Comment by xqXQzzz1** [comment]
> 
> 
> @xqXQzzz1 做不到， clash 不会在重启之间保持节点选择状态。 而网页客户端 和 clash 的生命周期又是完全独立的，网页端就算记录了状态也没法第一时间传递给 clash。

已经通过其他方法实现
