### ISSUE TITLE
浏览器打开报错怎么解决

### ISSUE THREAD

**Issue by lamu0102** [haishanh/yacd#511]
SyntaxError
invalid property id
Call Stack
 ["./node_modules/recoil/dist/recoil.development.js"]
  vendors~app.js:7999:1
 __webpack_require__
  runtime.js:880:13
 hotCreateRequire/fn
  runtime.js:168:20
 undefined
  node_modules/recoil/dist/index.js:15:20
 ["./node_modules/recoil/dist/index.js"]
  vendors~app.js:7987:1
 __webpack_require__
  runtime.js:880:13
 hotCreateRequire/fn
  runtime.js:168:20
 undefined
  src/components/Root.js:16:64
 undefined
  src/components/Root.js:2:29
 ["./src/components/Root.js"]
  app.js:794:1

**Comment by haishanh** [comment]
@lamu0102 你这个是 `yarn start` 开发的时候 遇到的吧。

你用的什么浏览器？这个问题是怎么触发的？

**Comment by haishanh** [comment]
新版本的非 docker 版本打开了 source map，也许可以看到更多信息吧。
我先 close 了。
