### ISSUE TITLE
大佬，能指点下clash API的问题吗？想利用插件实现节点记忆

### ISSUE THREAD

**Issue by flyhigherpi** [haishanh/yacd#512]
put / proxies/:name 含emoji 中文，请教下参数需如何处理呢？
比如：
获取节点：
curl -X GET "http://192.168.2.1:9990/proxies/%f0%9f%8d%8e%20%e8%8b%b9%e6%9e%9c%e6%9c%8d%e5%8a%a1" -v 
已经测试OK
比如策略组：🌍 国外媒体
选定节点：🇭🇰 香港4
尝试 curl  -v -H "Content-Type: application/json; charset=utf-8" -X PUT "http://192.168.2.1:9990/proxies/%f0%9f%8d%8e%20%e8%8b%b9%e6%9e%9c%e6%9c%8d%e5%8a%a1" -d '{"name": "🇭🇰 香港4"}'
报节点不存在，转码的是苹果服务。
如何才能更新进去呢
感谢！

**Comment by flyhigherpi** [comment]
搞定了

**Comment by xqXQzzz1** [comment]
> 搞定了

什么插件呀？
