### ISSUE TITLE
在Connections页面对DL、UL、对应Speed、Time排序时能否优先降序排列？

### ISSUE THREAD

**Issue by gyj1109** [haishanh/yacd#514]
在Connections页面点击DL、UL、DL Speed、UL Speed和Time排序时，点一下升序，再点一下降序。能否改成点一下降序？大多数人需要的应该是流量最多、速度最快、连接最久的那个。谢谢

**Comment by gyj1109** [comment]
其余几列（Host、Chains、Rule、Source、Destination IP、Type）可以保持点一下升序。这几列都是字母序，点一下降序反而违反常识。

**Comment by haishanh** [comment]
@gyj1109 

> 在Connections页面点击DL、UL、DL Speed、UL Speed和Time排序时，点一下升序，再点一下降序。能否改成点一下降序？大多数人需要的应该是流量最多、速度最快、连接最久的那个。

那其实当前相当于是多了一个没什么用的功能。这会有什么问题吗？

**Comment by gyj1109** [comment]
> 那其实当前相当于是多了一个没什么用的功能。这会有什么问题吗？

比如我想确认当前B站下载的流量是否直连，但我不确定B站的下载服务器域名。这时最好的办法就是按下载速度降序排列，那个在拼命下载的就是。我经常做这样的操作，但每次都要点两次才能降序，所以希望能优先降序排列。

**Comment by gyj1109** [comment]
没有仔细研究过代码，是只要在这里加if，修改`desc`就行了吗？
https://github.com/haishanh/yacd/blob/31fbdfc3df61441f7caf507c83a8e38c503bd7ef/src/components/ConnectionTable.js#L40-L47

**Comment by haishanh** [comment]
@gyj1109 对 差不多是这个地方 我改下

**Comment by haishanh** [comment]
我发了 `v0.2.3`

这部分的改动 https://github.com/haishanh/yacd/commit/29027c897ae6c003886e2a5995ef554a421d86e4
