### ISSUE TITLE
关于左上角LOGO

### ISSUE THREAD

**Issue by Synchronized1** [haishanh/yacd#517]
大佬,最新版怎么左上角LOGO删除了...突然感觉少了点什么?😂
这是出于什么考虑?
![image](https://user-images.githubusercontent.com/58451554/89723988-142cff00-da30-11ea-979b-631c086d87f3.png)

**Comment by haishanh** [comment]
@Synchronized1 这个 web app 是个工具型的应用，我只是觉得当前 logo 的设计风格不太搭。我也还没想好 只是试试当前的布局 也许以后就加回来
