### ISSUE TITLE
希望docker能增加arm64版本

### ISSUE THREAD

**Issue by xjqxziii** [haishanh/yacd#519]
希望docker镜像能增加arm64的版本

**Comment by haishanh** [comment]
@xjqxziii 不了解 arm，我应该是要用 docker hub 上 [arm64v8](https://hub.docker.com/u/arm64v8) 用户下的 image 做 base 吗？ 比如 [arm64v8/nginx](https://hub.docker.com/r/arm64v8/nginx/)

**Comment by kallydev** [comment]
我可以解决这个需求，有兴趣接受 PR 么
