### ISSUE TITLE
大佬2.6强制输出日志是否占用设备内存

### ISSUE THREAD

**Issue by flyhigherpi** [haishanh/yacd#524]
设置的error但是强制输出日志，也看了并没有写自己指定的clash启动日志文件。
想知道这些日志是否占用设备空间。路由上跑的

**Comment by haishanh** [comment]
clash 的日志输出如果是到指定文件的话 肯定会占用设备空间 你得自己 monitor 一下

这与 yacd 并没有什么关系

**Comment by flyhigherpi** [comment]
> clash 的日志输出如果是到指定文件的话 肯定会占用设备空间 你得自己 monitor 一下
> 
> 这与 yacd 并没有什么关系

是当前设置为error级别。但是日志强制以info级别输出。确认下是否为bug
