### ISSUE TITLE
ws conection failed

### ISSUE THREAD

**Issue by op69qs** [haishanh/yacd#526]
`WebSocket connection to 'ws://127.0.0.1:7892/connections' failed: Unknown reason`
browser version: Edge 86.0.601.1 

导致Connections 无法查看链接详情
推测是ws跨域问题

**Comment by haishanh** [comment]
@op69qs 你可以试试用 http://localhost:7892 作为 base URL

**Comment by leoorz** [comment]
> @op69qs 你可以试试用 http://localhost:7892 作为 base URL

遇到同样的问题，按作者的办法修改就可以了
```
mode: Rule
log-level: info
external-controller: http://localhost:9090
```

**Comment by op69qs** [comment]
可以了....这是什么问题

**Comment by op69qs** [comment]
该问题又出现了，现在这边使用docker 部署
使用chrome(90.0.4430.30) 无法添加 http://localhost:7892和http://127.0.0.1:7892
console报错
`GET http://localhost:7892/configs net::ERR_FAILED`
该地址可以正常get情况返回json

**Comment by cglol** [comment]
尝试把config.yaml 里的端口换掉可正常打开，如下

     external-controller: 127.0.0.1:56789
