### ISSUE TITLE
Oops, something went wrong!

### ISSUE THREAD

**Issue by xy9860** [haishanh/yacd#527]
window10 新版edge浏览器
![2BJUGBNV%FSB4CGZHG0`MRP](https://user-images.githubusercontent.com/25838633/93298030-0df72300-f825-11ea-8455-86f0deb80031.png)

**Comment by haishanh** [comment]
没想明白 为什么会有这个问题
你尝试一下清空一下 local storage 吧

我没有 edge，下面是 chrome 的截图， edge 应该差不多吧

![image](https://user-images.githubusercontent.com/1166872/93344021-bfb54480-f863-11ea-8660-cca681b387da.png)

**Comment by xy9860** [comment]
清除数据以后正常了
