### ISSUE TITLE
0.2.7 的建议

### ISSUE THREAD

**Issue by suiboli314** [haishanh/yacd#528]
- scroll 区域的判定有点不够舒适. 系统,浏览器没变, `0.2.5` -> `0.2.7`, 体验感觉变了很多.. see [video](https://vimeo.com/459445810).
- 希望 `api base url` 能够自动添加 `http(s)` header

specs: 
yacd 0.2.7,
iOS 14,
safari

**Comment by haishanh** [comment]
不好意思，问题太久远 先 close 了。
有需要可以 reopen
