### ISSUE TITLE
请问这个面板内网穿透怎么弄？

### ISSUE THREAD

**Issue by jitashenshi** [haishanh/yacd#530]
我用FRP内网穿透访问路由器，其他界面都能正常访问使用，就是这个yacd界面不行。能打开，但是无任何数据。
![image](https://user-images.githubusercontent.com/69400033/94039090-d9253600-fdf9-11ea-8a04-a937fff52fe2.png)

**Comment by haishanh** [comment]
@jitashenshi 你也需要给 HTTP 192.168.98.1:9090 配置穿透吧

**Comment by sonyxu** [comment]
> @jitashenshi 你也需要给 HTTP 192.168.98.1:9090 配置穿透吧

大佬好，这个需求可能是有的，需要远程控制而又不想对公网穿透9090端口，如果能直接在服务器上设置直接连接127.0.0.1:9090
那么穿透出来的网页只需要设置一个网页加密就好了。非常喜欢这个ui希望，希望能支持这个功能或者大概说一下怎么改？因为需要的人可能不是很多所手动修改一下也可以的

再次多谢大神的劳动。

**Comment by sonyxu** [comment]
> > @jitashenshi 你也需要给 HTTP 192.168.98.1:9090 配置穿透吧
> 
> 大佬好，这个需求可能是有的，需要远程控制而又不想对公网穿透9090端口，如果能直接在服务器上设置直接连接127.0.0.1:9090
> 那么穿透出来的网页只需要设置一个网页加密就好了。非常喜欢这个ui希望，希望能支持这个功能或者大概说一下怎么改？因为需要的人可能不是很多所手动修改一下也可以的
> 
> 再次多谢大神的劳动。

昂今天翻看了一下clash api 发现面板本身是没法直接这么做的，至少得写个可以发出网络请求的插件，但是直接用clash 似乎有-ext-ui 可以直接做到。
所以打扰了。。。。
