### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by MiRaIOMeZaSu** [haishanh/yacd#532]
在heroku上搭建yacd，搭建成功后添加API Base URL时显示Failed to connect，
![image](https://user-images.githubusercontent.com/49987193/95004598-defff000-061f-11eb-8c41-c136990a7799.png)
在与clash在同一服务器上搭建的yacd能够添加并访问成功，该clash开放的api已开放防火墙，能够在浏览器上访问，同时在heroku端尝试用curl访问服务器上的api也能成功得到相应的{"hello": "clash"}返回，请问这是哪个步骤出问题了呢？

**Comment by MiRaIOMeZaSu** [comment]
好吧，再次试了下发现是https无法访问我那个http的api的原因

**Comment by BruceLee569** [comment]
我也是一样的问题，搞了半天，最后还是通过http网页弄好了。
