### ISSUE TITLE
如何填写API Base URL?

### ISSUE THREAD

**Issue by DebuAqua** [haishanh/yacd#533]
没有在本仓库和  Dreamacro/clash 中找到任何对 API Base URL 的描述。
请问应该如何填写 API Base URL 才能使用 yacd 面板的全部功能？

**Comment by haishanh** [comment]
@DebuAqua 格式差不多是 `http://a.b.c:1234`

**Comment by haishanh** [comment]
给这种情况下的错误信息里面加了提示

**Comment by BruceLee569** [comment]
如果面板页是https，添加时显示不能发送http请求哦。。。
