### ISSUE TITLE
最新版本在ios浏览器无法正确显示

### ISSUE THREAD

**Issue by nkta3m** [haishanh/yacd#535]
iOS下的chrome 和 firefox 都无法正确显示，之前的版本没问题

**Comment by juewuy** [comment]
最新的文件好像有问题，我试了也是不显示，而且体积变大了好多

**Comment by haishanh** [comment]
应该跟我把 build 工具从 webpack 4 升级到 5 有关系。

要是有更多信息 我可能才知道是怎么回事

我自己现在用的 iOS 14.0.1  Chrome 和 Safari 上没有问题。

@juewuy 体积变大可能是 因为我现在默认生成了 debug 用的 source map 了，如果不需要可以自己删掉。 Docker image 里面我都删掉了。

https://github.com/haishanh/yacd/blob/0d4b92de5c34e83d63d95ef9304dc7815bea6c63/Dockerfile#L10

**Comment by nkta3m** [comment]
我的设备是iOS13，手上没有iOS14，已退回0.27

**Comment by xqXQzzz1** [comment]
> 我的设备是iOS13，手上没有iOS14，已退回0.27

弱弱地问一句，怎么在ios设备上用clash？挂的路由器吗？

**Comment by nkta3m** [comment]
嗯，路由器上clash
