### ISSUE TITLE
使用 service worker 来实现缓存功能

### ISSUE THREAD

**Issue by CzBiX** [haishanh/yacd#536]
作为一个可能会经常打开访问的界面，如果能通过缓存实现加速访问就太棒了。

**Comment by haishanh** [comment]
主要是因为 service worker 必须要求 yacd 是用 https serve 的。

除非用 Nginx 或 Caddy 等工具反代 Clash 的 controller API，不然很多浏览器也会阻止从 https site 上调用 http 的 API。这样折腾的用户应该不多。

也许以后有时间会考虑实现一下吧。

**Comment by CzBiX** [comment]
Chrome 系允许在 HTTPS domain 用 HTTP 访问 localhost，这已经覆盖大部分用户。
另外 Google 提供的 workbox 可以相对轻松的实现离线功能。

**Comment by haishanh** [comment]
Implemented in `v2.0.10`

An HTTPS version is available on Netlify in case someone needs it. https://yacd.netlify.app

**Comment by CzBiX** [comment]
GitHub 本身就支持 HTTPS，https://yacd.haishan.me/ 也可以，不需要额外的 Netlify。

**Comment by haishanh** [comment]
噢 我当时故意关掉了 gh-pages 的 enforce https 选项，没想起来还是可以 https 的
