### ISSUE TITLE
[建议]缩短显示节点类型

### ISSUE THREAD

**Issue by AzurLab** [haishanh/yacd#539]
建议在节点信息的中缩短显示节点类型，或者仅在移动端页面缩短，比如将shadowsocks缩短为ss显示，以留出显示延迟的空间。

如果节点名称不长，shadowsocks这个显示很长，最小大小的方框没有剩余空间来显示延迟，测试延迟之后，方框会增宽，而延迟位数不同的话，方框就会不一样宽，界面就会比较的凌乱。

感谢开发

**Comment by haishanh** [comment]
改了，暂时只是把 Shadowsocks 显示成了 SS。其他类型名字长度还行,就没有改。

**Comment by AzurLab** [comment]
谢谢，辛苦了
