### ISSUE TITLE
Log 信息的显示问题

### ISSUE THREAD

**Issue by nkta3m** [haishanh/yacd#541]
我的问题是0.27版本，即使config里面设置log的级别为silent，log依然滚动显示，这是是否会clash的性能？
![149979B3-8998-47A2-8A75-06C154DE93AB](https://user-images.githubusercontent.com/13484700/98604842-66c3d300-231f-11eb-975c-aae37276c76a.jpeg)
![03AE2D8E-5E17-4DFD-9BA8-16B761986720](https://user-images.githubusercontent.com/13484700/98604849-69262d00-231f-11eb-9798-712314d3d93d.jpeg)

**Comment by qin9125** [comment]
只有25版本是正常的，25之后都是疯狂输出日志，不知道为啥，0.2.12最新的依旧疯狂输出日志

**Comment by escape0707** [comment]
这个日志界面不能暂停日志的输出，导致发现问题时观察困难啊。
