### ISSUE TITLE
页面怎么支持https

### ISSUE THREAD

**Issue by LzwCracker** [haishanh/yacd#544]
现在访问是白板
![image](https://user-images.githubusercontent.com/18252512/99890671-d2515d00-2c9c-11eb-8a47-9064f4a9bd4e.png)

**Comment by haishanh** [comment]
不用 https 的话，同一个 url 可以访问吗？

不清楚你这个环境，所以可能帮不了什么

**Comment by LzwCracker** [comment]
@haishanh  貌似含有css页面都自动跳转https
以前貌似没开ssl 是可以访问的

**Comment by haishanh** [comment]
@LzwCracker 应该是配置问题吧 所有的资源应该都是以相对路径进行加载的

**Comment by sabersalv** [comment]
确认不能访问.

Reproduce
1. OpenWRT 开启ssl访问
2. 打开https://192.168.1.1


https模式下面
<img width="958" alt="Screen Shot 2020-11-25 at 11 23 59 PM" src="https://user-images.githubusercontent.com/2525544/100247980-ea173280-2f75-11eb-9990-d6c3ff40fde1.png">

http模式下面
<img width="767" alt="Screen Shot 2020-11-25 at 11 25 37 PM" src="https://user-images.githubusercontent.com/2525544/100248019-f4d1c780-2f75-11eb-8bab-34f79a0adcec.png">

**Comment by XKangs** [comment]
我也遇到这个问题了
因为承载yacd的服务器配置了https(自签名证书)而clash的管理api不支持https
所以加载时浏览器会block-mixed content导致yacd无法正常加载
目前我能想到我解决方法是
1 不用本地，直接用现成的http://yacd.haishan.me/
2 先把数据通过https发到nginx，再由nginx转发
--------------
浏览器版本：Chrome 88.0

**Comment by BruceLee569** [comment]
> 我也遇到这个问题了
> 因为承载yacd的服务器配置了https(自签名证书)而clash的管理api不支持https
> 所以加载时浏览器会block-mixed content导致yacd无法正常加载
> 我之前还在想有没有什么http的header可以让浏览器允许这种情况（就好像跨域的问题加个header就好了），结果找了一圈发现没有
> 
> ## 目前我能想到我解决方法是
> 1 不用本地搭建的，直接用现成的 http://yacd.haishan.me/
> 2 先把数据通过https发到nginx，再由nginx转发
> 浏览器版本：Chrome 88.0

请问nginx转发怎么设置呢？今天我鼓捣了半天，最后还是跟方法一一样弄了个二级域名http成功了，如果想要https还是不知道怎么解决。

**Comment by 1nfsr** [comment]
> > 我也遇到这个问题了
> > 因为承载yacd的服务器配置了https(自签名证书)而clash的管理api不支持https
> > 所以加载时浏览器会block-mixed content导致yacd无法正常加载
> > 我之前还在想有没有什么http的header可以让浏览器允许这种情况（就好像跨域的问题加个header就好了），结果找了一圈发现没有
> > ## 目前我能想到我解决方法是
> > 1 不用本地搭建的，直接用现成的 http://yacd.haishan.me/
> > 2 先把数据通过https发到nginx，再由nginx转发
> > 浏览器版本：Chrome 88.0
> 
> 请问nginx转发怎么设置呢？今天我鼓捣了半天，最后还是跟方法一一样弄了个二级域名http成功了，如果想要https还是不知道怎么解决。

nginx反理WebSocket
样例 https://github.com/1nfsr/openwrt-actions/blob/main/base-files/etc/nginx/conf.d/clash-wss.conf

**Comment by 21ki** [comment]
一样的问题

**Comment by PhantomZheng** [comment]
目前我用的 Docker-YACD + Docker-Caddy 方案：写到同一个 docker-compose.yml 再加一个 Caddyfile 就搞定。
