### ISSUE TITLE
[其他] github上关注release信息后收不到通知

### ISSUE THREAD

**Issue by h3fang** [haishanh/yacd#545]
![image](https://user-images.githubusercontent.com/1715589/100039066-80950800-2e3f-11eb-8c4e-867e0e374c7a.png)
如图，又不想关注所有信息，只能定期来看看有没有更新。
其他的仓库可以，不知道为什么
![image](https://user-images.githubusercontent.com/1715589/100039410-25afe080-2e40-11eb-85a9-30e35a7fbb21.png)

**Comment by haishanh** [comment]
@h3fang 可能是因为我其实用的不是 github 的 release。我一直用的是 git tag

下个 release 开始，我也用 github release 好了。

**Comment by h3fang** [comment]
收到通知了，感谢
