### ISSUE TITLE
[Feature Request] 请求添加一键更新所有proxy-providers/rule-providers的按钮

### ISSUE THREAD

**Issue by R3pl4c3r** [haishanh/yacd#551]
由于rule/proxy组比较多，希望可以增加这样一个按钮一次性更新

**Comment by lvhe19880210** [comment]
provider更新按钮还是蛮有用的，这样可以随时更新了，希望作者考虑

**Comment by lvhe19880210** [comment]
> 一键更新所有provider貌似clash for windows也没支持呢
刚才更新了 发现clash for windows有这个功能 这个功能确实挺需要的 忘作者更新

**Comment by lvhe19880210** [comment]
> 由于rule/proxy组比较多，希望可以增加这样一个按钮一次性更新

确实很需要这个功能

**Comment by haishanh** [comment]
`v0.2.15` 中实现了这个功能
