### ISSUE TITLE
How to reset yacd?

### ISSUE THREAD

**Issue by bingo10k** [haishanh/yacd#555]
Clash+Yacd, It is wrong when I delete the 127.0.0.1:9090, Clash works rightly.How to fix it,Plz help 
![image](https://user-images.githubusercontent.com/76892381/103471100-9985c700-4db6-11eb-879d-aa8c6980875d.png)

**Comment by haishanh** [comment]
@bingo10k Which browser are you using? Do you know how to open the dev tools console? If you know that, you may find some error information there.

**Comment by CoelWu** [comment]
I have also encountered this error. The same way to reproduce the issue as @bingo10k, when there was no url left, the message was shown.
I'm using Brave Browser which was based on Chromium.
![brave_y8VspS3MJU](https://user-images.githubusercontent.com/76829607/109807784-54b8c800-7c61-11eb-87f3-43d33a1acec0.png)
