### ISSUE TITLE
希望支持高亮鼠标悬停的当前行

### ISSUE THREAD

**Issue by ArriettyQAQ** [haishanh/yacd#556]
具体需要在规则、连接和日志这三个页面支持该特性，不然屏幕大了实在不知道自己鼠标选到哪一行了

尤其是规则页面，辛苦大佬了。

**Comment by haishanh** [comment]
应该主要问题是 规则页面 rule provider 右边的刷新按钮，只有在 hover 的时候才会显示，所以很难看清楚哪一个吧。因为我很少去刷新 rule provider，用的屏幕也不大，所以也是前几个意识到这个问题，已经做了一些改进。

不好意思，这个 issue 已经开了这么久才来回复。

**Comment by ArriettyQAQ** [comment]
> 应该主要问题是 规则页面 rule provider 右边的刷新按钮，只有在 hover 的时候才会显示，所以很难看清楚哪一个吧。因为我很少去刷新 rule provider，用的屏幕也不大，所以也是前几个意识到这个问题，已经做了一些改进。
> 
> 不好意思，这个 issue 已经开了这么久才来回复。

开源产品，没什么不好意思的，等更新。
