### ISSUE TITLE
大佬，tproxy udp显示问题。

### ISSUE THREAD

**Issue by flyhigherpi** [haishanh/yacd#561]
![IMG_20210124_080445_142](https://user-images.githubusercontent.com/67776691/105617665-066f0880-5e1b-11eb-8d00-7267016e651c.jpg)
TPROXY(UDP)显示为REDIR(UDP)了
望修复。

**Comment by cielpy** [comment]
这个其实是 Clash 内核的问题，https://github.com/Dreamacro/clash/blob/83efe2ae57ccae2b4b8626c2f88bfb5a391f73f2/proxy/redir/udp.go#L78

内核把 UDP 标记成 redir 了，实际上是 TProxy CC @Dreamacro

**Comment by Dreamacro** [comment]
fixed

**Comment by flyhigherpi** [comment]
> fixed

nice
