### ISSUE TITLE
如何切换连接到的 clash 

### ISSUE THREAD

**Issue by Z1Wu** [haishanh/yacd#562]
打开 yacd.haishan.me 就会默认连接到 127.0.0.1:9090，之后想切换到别的 clash 后端(other_addr:other_port) 应该如何操作？能否添加一个选择连接的后端的功能。
- 使用 chrome 的无痕模式依然会默认连接到 127.0.0.1:9090

**Comment by wych42** [comment]
Config 页面里有一个 Switch Backends 选项。

**Comment by Z1Wu** [comment]
👌，多谢。
