### ISSUE TITLE
Config 与 Logs 的位置

### ISSUE THREAD

**Issue by imldy** [haishanh/yacd#565]
![image](https://user-images.githubusercontent.com/53949747/107878070-3d60a780-6f0b-11eb-9bcc-4b7e06253b31.png)

为什么要把Config放倒数第二，反倒把Logs放最后呢。不应该是Config决定了其他几项的显示吗，有点反直觉……

**Comment by haishanh** [comment]
这两项的顺序，确实不是那么的显而易见，但我也不觉得 Logs 就应该拍前面。我也不大可能为这个再实现一个 sidebar item 自定义排序的功能。
