### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by Naughty-Monkey** [haishanh/yacd#571]
使用docker分别起了yacd和clash服务，浏览器可以打开external controler页面，返回`{"hello":"clash"}`。
而yach始终是`Failed to connect`。换用本地npm环境启动yacd是同样的现象。
![image](https://user-images.githubusercontent.com/13866870/112422776-60814100-8d6c-11eb-9476-4ec07ebcc34f.png)
![image](https://user-images.githubusercontent.com/13866870/112422830-77279800-8d6c-11eb-85d5-8bff60a8c303.png)

**Comment by Naughty-Monkey** [comment]
啊啊啊，看错了，是在抱歉

**Comment by lujiaweicy** [comment]
把 external-controller: 改成 ‘0.0.0.0:9090’

**Comment by taikelaoleji** [comment]
clash要添加端口映射9090给yacd
