### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by piaoyun** [haishanh/yacd#580]
添加链接提示错误：Not Found

用的是服务器的外网IP呢。服务器是腾讯云国内服务器呢，docker版本运行，clash也运行起来了

就是yacd添加链接的时候，提示报错。

**Comment by haishanh** [comment]
要确保浏览器可以访问 clash external controller API，另外浏览器可能也会因为一些安全规则而不允许跨域 API 调用。

**Comment by RobbieDragon233** [comment]
> ller API，另

跨域这个有解吗？yacd和clash本身是分开的，我不管咋输入都被跨域拦住了（network中所有请求均为strict-origin-when-cross-origin）
