### ISSUE TITLE
关于https的建议

### ISSUE THREAD

**Issue by lampb0y** [haishanh/yacd#583]
由于作者已经提供了源码，我们能否本地建一个web项目，并打包成war包，丢到tomcat，并运行，我自己尝试过，事实证明可行，但是否具有https的安全性？

**Comment by haishanh** [comment]
不懂 tomcat。yacd build 之后就是一堆静态文件，基本上是个 web server 都能 serve 这些文件。
关键问题在于你也需要反代 clash 的 API 提供 https 的 API。不然大部分时候，浏览器不允许从 https 的网页应用调用 http 的 API。
