### ISSUE TITLE
初始界面无法连接绑定IP的Clash

### ISSUE THREAD

**Issue by adrianzhang** [haishanh/yacd#617]
Clash只监听固定的LAN IP。从另一个机器访问。http://LAN_IP:19090，能够得到Clash返回的提示。
在Clash机器上，把yacd 0.3.2 zip包解压后的public中的全部文件放入clash目录folder文件夹。
访问http://LAN_IP:19090/ui/
输入URL 后点Add，没反应。点下方的http://127.0.0.1:7892，当然连不上。
浏览器：Safari 14.0（MacOS 10.15.6/Catalina）和Chrome 版本 91.0.4472.114（正式版本） (x86_64)

**Comment by haishanh** [comment]
@adrianzhang 你得看一下 你 Clash 配置文件中的 `external-controller` 的 port 是什么。

**Comment by adrianzhang** [comment]
> @adrianzhang 你得看一下 你 Clash 配置文件中的 `external-controller` 的 port 是什么。

external-controller: LAN_IP:19090

**Comment by adrianzhang** [comment]
> @adrianzhang 你得看一下 你 Clash 配置文件中的 `external-controller` 的 port 是什么。

很奇怪，今天再试又可以Add了。工作一切正常。配置没有改过任何东西。大概是网络上出的问题吧。谢谢！可以关闭了。
