### ISSUE TITLE
bug: if "name" field of a proxy-group ends with a space, its active node cannot be changed

### ISSUE THREAD

**Issue by Un1Gfn** [haishanh/yacd#619]
#### Environment

* yacd ~~0.3.2~~ 0.3.3 applies as well
* clash -v `Clash 1.6.5 linux amd64 with go1.16.5 unknown time`
* Arch Linux, with Linux 5.4.129
* Firefox 90.0 (64-bit)

#### Nnormal behavior

1. Grab [minimal test config](https://github.com/Un1Gfn-network/clash/blob/master/bug.yaml) and rename to config.yaml
1. Run clash
1. Visit http://127.0.0.1:9090/ui
1. Expand `GroupA`
1. `Node1` is highlighted
1. Click `Node3`
1. `Node3` is highlighted
1. Refresh the browser page (<kbd>Ctrl</kbd>+<kbd>F5</kbd>)
1. `Node3` is still highlighted :heavy_check_mark:
1. Click `Node2`
1. `Node2` is highlighted
1. Refresh the browser page (<kbd>Ctrl</kbd>+<kbd>F5</kbd>)
1. `Node2` is still highlighted :heavy_check_mark:
1. Everything works fine

#### To reproduce the bug

1. Rename `- name: "GroupA"` to `- name: "GroupA "` in config.yaml
1. Run clash
1. Visit http://127.0.0.1:9090/ui
1. Expand `GroupA `
1. `Node1` is highlighted
1. Click `Node3`
1. `Node3` is highlighted
1. Refresh the browser page (<kbd>Ctrl</kbd>+<kbd>F5</kbd>)
1. `Node1` is highlighted :x:
1. Click `Node2`
1. `Node2` is highlighted
1. Refresh the browser page (<kbd>Ctrl</kbd>+<kbd>F5</kbd>)
1. `Node1` is highlighted :x:

#### Summary

`GroupA ` is stuck with `Node1`. Cannot swith to any other node.

This might be a bug from Dreamacro/clash instead of yacd.

**Comment by haishanh** [comment]
Sorry for such a late reply, it's a bug of yacd. Will fix.

**Comment by haishanh** [comment]
The fix is in `master` branch.
