### ISSUE TITLE
使用chromeapp功能来方便访问

### ISSUE THREAD

**Issue by soloopooo** [haishanh/yacd#621]
如题，现在最新版本的yacd依然不支持自动提示添加chromeapp，仅能够手动添加快捷方式后变为chromeapp。
如果使用chromeapp功能，可以大大方便用户，无需输入地址或者在收藏夹寻找即可快速打开，且更有应用风格。
可以详见youtube，twitter等使用chromeapp功能的网站。
![image](https://user-images.githubusercontent.com/36123081/125905303-803af616-d46b-4d6e-832a-663611cd378b.png)

**Comment by fxzxmicah** [comment]
我同意你的说法，但是手动安装后效果是相同的，是否有提示就看作者的想法了，个人观点认为可以有但是非必要。
