### ISSUE TITLE
Help Connection

### ISSUE THREAD

**Issue by adisubagja** [haishanh/yacd#622]
![Screenshot_20210717-135226_Via](https://user-images.githubusercontent.com/15952175/126028800-af9ea909-ec7d-4c11-9195-584d7b3ad9b5.png)

Why always showing ip.
Not showing hostname i've done with set a rule for facebook,youtube,instagram for proxy and set google using direct

**Comment by haishanh** [comment]
Sorry for such a delayed response. This is not exactly a yacd issue, it's likely related to the [clash dns setting](https://github.com/Dreamacro/clash/wiki/configuration).
