### ISSUE TITLE
docker pull 0.3.3版本，为何关于中是0.3.2？

### ISSUE THREAD

**Issue by borpubi** [haishanh/yacd#629]
截图如下：
![image](https://user-images.githubusercontent.com/28093885/128120118-3257fd46-72b8-4c3c-a00a-fcc7ed5011e9.png)
![image](https://user-images.githubusercontent.com/28093885/128120130-7185f488-f188-4723-b929-cf80150e6a43.png)

**Comment by haishanh** [comment]
可能只是那次 release 有问题吧。
About 显示的 版本号来自 `package.json` 文件 `version` 这个字段。正常情况下发布版本后，两个应该是一致的。
