### ISSUE TITLE
开源许可

### ISSUE THREAD

**Issue by ibigbug** [haishanh/yacd#645]
项目是否允许商用？

**Comment by Un1Gfn** [comment]
@ibigbug 如有顧慮可用[clash-dashboard](https://github.com/Dreamacro/clash-dashboard) (MIT)

**Comment by haishanh** [comment]
可以的，其实一直是 MIT ，只是一直忘了加单独的 LICENSE 文件
https://github.com/haishanh/yacd/blob/1174878e8c152f51db308646e6d7e4a7cc06e271/package.json#L29
