### ISSUE TITLE
Automatic dark mode?

### ISSUE THREAD

**Issue by Goose-Bomb** [haishanh/yacd#652]
Hi, I'd really like the YACD to switch dark/light color theme automatically to match the macOS system theme. Is there any plan to add this feature? Since YACD already has the theme switching button, it should be facile to add a new option for the “auto” theme mode.

You can utilize the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) feature to implement this.

**Comment by haishanh** [comment]
Close as already implemented.
