### ISSUE TITLE
建议优化chrome网页页面中概览与规则的显示效果

### ISSUE THREAD

**Issue by China-Huanghe** [haishanh/yacd#657]
![image](https://user-images.githubusercontent.com/77739994/147027452-e5953893-c24a-4cce-b6a2-135e72f628f6.png)
概览页面中空白内容过多
![image](https://user-images.githubusercontent.com/77739994/147027492-8123a0a4-6a73-492e-a71d-d0c435d1da01.png)
规则页面中空白内容过多

**Comment by haishanh** [comment]
同意，但事实上作为一个纯 web 应用，yacd 其实并没有办法拿到非常丰富的信息来显示。
如果有哪些比较有用的信息， clash 有提供相应的 API 而 yacd 却没有显示的，可以提出来再开 issue。
