### ISSUE TITLE
使用Proxy-Provider时，无法测速

### ISSUE THREAD

**Issue by La-Hire** [haishanh/yacd#659]
同样节点，用subconverter转换的正常测速，用Proxy-Provider引入的无反应（组中只有Provider和Direct，看F12无GET delay信息 返回）
换其他面板正常

**Comment by toddlerya** [comment]
> 同样节点，用subconverter转换的正常测速，用Proxy-Provider引入的无反应（组中只有Provider和Direct，看F12无GET delay信息 返回） 换其他面板正常

+1

**Comment by haishanh** [comment]
应该修好了 感谢反馈
