### ISSUE TITLE
希望增加订阅管理功能

### ISSUE THREAD

**Issue by dmzlingyin** [haishanh/yacd#664]

**Comment by everstu** [comment]
管理面板API:
https://clash.gitbook.io/doc/restful-api
如果clash没提供API是无法支持的.

**Comment by dmzlingyin** [comment]
> 管理面板API: https://clash.gitbook.io/doc/restful-api 如果clash没提供API是无法支持的.

clash提供了一个重新加载配置文件的接口，应该是可以通过订阅链接下载最新的配置文件，然后调用接口热更新配置文件。

**Comment by haishanh** [comment]
这个重新加载配置文件的接口 `PUT /configs` 需要提供文件路径这个参数
要实现订阅 需要有下载配置文件到 clash 所在的文件系统，除非 clash 提供这个功能或者自己实现一个后端，不然做不到。

**Comment by rebron1900** [comment]
> 这个重新加载配置文件的接口 `PUT /configs` 需要提供文件路径这个参数 要实现订阅，就需要下载配置文件到 clash 所在的文件系统，除非 clash 提供这个功能或者自己实现一个后端，不然做不到。

好奇clash咋不提供这方面的api，因为安全问题么？
