### ISSUE TITLE
希望能支持prometheus exporter

### ISSUE THREAD

**Issue by deanmax** [haishanh/yacd#665]
#### 希望能有一个export给prometheus scrape, 暴露如以下一些关键metrics:
- 即时上传/下载速率
- 总上传/下载流量(labelling区分是走Direct还是走Proxy)
- Active连接数
- 按请求网址区分的流量大小
- 其他辅助metrics

**Comment by haishanh** [comment]
这些数据更应该是 backend (clash) 来提供。可以考虑用闭源版的 clash，其中有 metrics 相关支持。

ref
- premium core feature [tracing](https://github.com/Dreamacro/clash/wiki/premium-core-features#tracing)
- [Dreamacro/clash-tracing](https://github.com/Dreamacro/clash-tracing)
