### ISSUE TITLE
本地直接打开index.html白屏，控制台：已拦截跨源请求

### ISSUE THREAD

**Issue by sky96111** [haishanh/yacd#667]
Firefox 96.0.3和Chromium 97.0.4692.99直接打开 yacd/public/index.html 均白屏，控制台输出：

Chromium:
 ```
index.html:1 Access to script at 'file:///home/sky96111/%E4%B8%8B%E8%BD%BD/yacd/public/assets/index.ee5bc09a.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
index.ee5bc09a.js:1 Failed to load resource: net::ERR_FAILED
index.html:1 Access to script at 'file:///home/sky96111/%E4%B8%8B%E8%BD%BD/yacd/public/assets/vendor.38e754a4.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
vendor.38e754a4.js:1 Failed to load resource: net::ERR_FAILED
index.html:1 Access to internal resource at 'file:///home/sky96111/%E4%B8%8B%E8%BD%BD/yacd/public/manifest.webmanifest' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

FireFox:
 `提示已拦截跨源请求：同源策略禁止读取位于 file:///home/sky96111/%E4%B8%8B%E8%BD%BD/yacd/public/assets/index.ee5bc09a.js 的远程资源。（原因：CORS 请求不是 http）`
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

**Comment by livin2** [comment]
你可以自己build一个
新增加依赖 `npm i @vitejs/plugin-legacy -D`


```diff
git diff .\vite.config.ts
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -3,6 +3,7 @@ import { VitePWA } from 'vite-plugin-pwa';
 import reactRefresh from '@vitejs/plugin-react-refresh';
 import * as path from 'path';
 import * as pkg from './package.json';
+import legacy from '@vitejs/plugin-legacy'

 // https://vitejs.dev/config/
 export default defineConfig(({ mode }) => ({
@@ -28,6 +29,9 @@ export default defineConfig(({ mode }) => ({
       strategies: 'injectManifest',
       base: './',
     }),
+    legacy({
+      targets: ['defaults', 'not IE 11']
+    })
   ],
   resolve: {
     alias: {
```
最后把`public/index.html`里的nomodule都删了就行了

**Comment by sky96111** [comment]
> 你可以自己build一个 新增加依赖 `npm i @vitejs/plugin-legacy -D`
> 
> ```diff
> git diff .\vite.config.ts
> --- a/vite.config.ts
> +++ b/vite.config.ts
> @@ -3,6 +3,7 @@ import { VitePWA } from 'vite-plugin-pwa';
>  import reactRefresh from '@vitejs/plugin-react-refresh';
>  import * as path from 'path';
>  import * as pkg from './package.json';
> +import legacy from '@vitejs/plugin-legacy'
> 
>  // https://vitejs.dev/config/
>  export default defineConfig(({ mode }) => ({
> @@ -28,6 +29,9 @@ export default defineConfig(({ mode }) => ({
>        strategies: 'injectManifest',
>        base: './',
>      }),
> +    legacy({
> +      targets: ['defaults', 'not IE 11']
> +    })
>    ],
>    resolve: {
>      alias: {
> ```
> 
> 最后把`public/index.html`里的nomodule都删了就行了

没有做过前端开发，不清楚是不是操作不对。做完这些操作后的控制台报错变成了
```
已拦截跨源请求：同源策略禁止读取位于 file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/assets/index.55025da8.js 的远程资源。（原因：CORS 请求不是 http）。

此文档不允许使用模块来源的 URI：“file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/assets/index.55025da8.js”。 [index.html:17:1](file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/index.html)

已拦截跨源请求：同源策略禁止读取位于 file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/assets/index-legacy.07d2f7dc.js 的远程资源。（原因：CORS 请求不是 http）。

此文档中不允许的 <script> 来源 URI：“file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/assets/index-legacy.07d2f7dc.js”。 [index.html:1:1](file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/index.html)
Uncaught (in promise) Error: file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/assets/index-legacy.07d2f7dc.js,  (SystemJS https://git.io/JvFET#3)

instantiate file:///home/sky96111/文档/yacd/public/assets/polyfills-legacy.1161319a.js:1
[polyfills-legacy.1161319a.js:1:66398](file:///home/sky96111/%E6%96%87%E6%A1%A3/yacd/public/assets/polyfills-legacy.1161319a.js)

Uncaught (in promise) TypeError: ServiceWorkerContainer.register: Script URL's scheme is not 'http' or 'https'
<anonymous> file:///home/sky96111/文档/yacd/public/registerSW.js:1
```

我先安装了yarn, npm17, nodejs 。在克隆的yacd仓库根目录执行
`yarn`
修改 vite.config.ts 后执行
`npm i @vitejs/plugin-legacy -D`
再执行
`yarn build`
替换public/index.html文件中所有的 “nomodule” 为 “ ”

Firefox仍然不能显示界面

**Comment by livin2** [comment]
Firefox把`file_unique_origin`关了就行，不过不建议这样做

**Comment by sky96111** [comment]
以前html是0后台无开销，目前是起了一个docker，稍微麻烦了点，其实没什么影响

**Comment by xTire** [comment]
> Firefox 96.0.3和Chromium 97.0.4692.99直接打开 yacd/public/index.html 均白屏，控制台输出：
> 
> （原因：CORS 请求不是 http）` https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
>
你给出的链接已经解释了问题的原因，感谢。

这时看上去可能需要一个http服务器来部署yacd了；或者按照livin2提到的办法来处理。
我这里使用如下方法临时的使用并对本机的clash进行配置：
$cd [yacd_path]/public
$python -m SimpleHTTPServer

本人小白，如果有更多的提示也请各位不要吝啬，先谢了。

**Comment by sky96111** [comment]
> > Firefox 96.0.3和Chromium 97.0.4692.99直接打开 yacd/public/index.html 均白屏，控制台输出：
> > 
> > （原因：CORS 请求不是 http）` https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
> >
> 你给出的链接已经解释了问题的原因，感谢。
> 
> 这时看上去可能需要一个http服务器来部署yacd了；或者按照livin2提到的办法来处理。
> 我这里使用如下方法临时的使用并对本机的clash进行配置：
> $cd [yacd_path]/public
> $python -m SimpleHTTPServer
> 
> 本人小白，如果有更多的提示也请各位不要吝啬，先谢了。

也可以使用readme里的docker镜像，它也附带了一个HTTP服务器

这个issue我暂时先开着，也恳请有能力的大佬能把livin2的方法提交一个pr

以下是我个人好奇的部分…因为我没有做过前端，只会写一点点静态界面和CSS，不太能理解npm这类的包工具。既然是浏览器限制了本地文件的跨源，是否意味着以后的本地HTML将无法加载外部js？通过npm引入一个包本质上还是本地文件访问外部js，为什么会改变浏览器行为？

**Comment by haishanh** [comment]
目前 build 出来的静态文件，本来就是需要服务器来 serve 的。推荐还是自己跑个 nginx 之类的来 serve 这些文件，或者直接用 docker image。

**Comment by sky96111** [comment]
> 目前 build 出来的静态文件，本来就是需要服务器来 serve 的。推荐还是自己跑个 nginx 之类的来 serve 这些文件，或者直接用 docker image。

好的。既然直接运行的方法已经不受支持了，README的描述是否需要修改一下呢？

**Comment by haishanh** [comment]
@sky96111 好吧 看 readme 我才发现 原来以前是支持。那应该很早之前把 build 系统从 webpack 换成 vite 的时候就坏掉了。

**Comment by 21ki** [comment]
> 你可以自己build一个 新增加依赖 `npm i @vitejs/plugin-legacy -D`
> 
> ```diff
> git diff .\vite.config.ts
> --- a/vite.config.ts
> +++ b/vite.config.ts
> @@ -3,6 +3,7 @@ import { VitePWA } from 'vite-plugin-pwa';
>  import reactRefresh from '@vitejs/plugin-react-refresh';
>  import * as path from 'path';
>  import * as pkg from './package.json';
> +import legacy from '@vitejs/plugin-legacy'
> 
>  // https://vitejs.dev/config/
>  export default defineConfig(({ mode }) => ({
> @@ -28,6 +29,9 @@ export default defineConfig(({ mode }) => ({
>        strategies: 'injectManifest',
>        base: './',
>      }),
> +    legacy({
> +      targets: ['defaults', 'not IE 11']
> +    })
>    ],
>    resolve: {
>      alias: {
> ```
> 
> 最后把`public/index.html`里的nomodule都删了就行了
有没有打包好的文件仓库地址
