### ISSUE TITLE
vite: not found

### ISSUE THREAD

**Issue by jszjgqq** [haishanh/yacd#678]
yarn build的时候报错。

npm i -g vite       或者  npm i vite 之后 yarn build 还是报错

root@gateway:/tmp/yacd# yarn build
yarn run v1.22.17
$ vite build
/bin/sh: 1: vite: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<img width="682" alt="iShot2022-03-08 13 41 22" src="https://user-images.githubusercontent.com/2629994/157173821-d962612b-267c-4ea8-9c50-928ffdf635ef.png">

**Comment by jszjgqq** [comment]
root@gateway:/tmp/yacd#  node -v
v12.22.5
root@gateway:/tmp/yacd# yarn -v
1.22.17

**Comment by haishanh** [comment]
你试下

```bash
yarn && yarn build
```

readme 有写

**Comment by jszjgqq** [comment]
> 你试下
> 
> ```shell
> yarn && yarn build
> ```
> 
> readme 有写

嗯，就是按照readme来的，yarn是装那些package.json 包，完了之后就是yarn build 打包，系统是 debian 11的，新装的纯净系统，然后就遇到了我上面所反馈的问题，后来也没搞定。。最后直接下了build好的zip包。

**Comment by haishanh** [comment]
你的情况应该还是依赖安装有问题

```bash
yarn
```

**Comment by jszjgqq** [comment]
> > 你试下
> > ```shell
> > yarn && yarn build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > readme 有写
> 
> 嗯，就是按照readme来的，yarn是装那些package.json 包，完了之后就是yarn build 打包，系统是 debian 11的，新装的纯净系统，然后就遇到了我上面所反馈的问题，后来也没搞定。。最后直接下了build好的zip包。

一开始提示 vite not found，然后apt install vite 之后 重新yarn build 依然报错，然后卸载，用npm i vite后重新build报错，然后卸载，继续尝试 npm i -g vite   然后build，还是报错，最后选择放弃。

**Comment by haishanh** [comment]
vite 不需要另外安装，属于 deps 的一部分。

**Comment by jszjgqq** [comment]
> vite 不需要另外安装，属于 deps 的一部分。

我又重新试了下，有可能是卡在下面这个报错？第一次我也遇到了，由于是eslint也没管，想着只是语法检测的，应该要求node大于14版本才行。

![Uploading iShot2022-03-10 09.38.44.png…]()

**Comment by jszjgqq** [comment]
> vite 不需要另外安装，属于 deps 的一部分。

是我草率了，当初针对eslint的报错想当然了，实际上卡住报错之后node_moudles的包一个都没装，所以build肯定出错，刚刚升级了下node，搞定。感谢大佬的指点。
