### ISSUE TITLE
主题

### ISSUE THREAD

**Issue by lloyd18** [haishanh/yacd#679]
老手机废物利用，看看网速和流量还不错 ~

大佬啥时候做个 #000000 纯黑的主题，oled屏应该能省电一些~

![Snipaste_2022-03-12_17-55-52](https://user-images.githubusercontent.com/10294460/158013413-58f363cd-20f8-40e0-b680-11f8e6f9f8fd.png)

**Comment by haishanh** [comment]
master branch 上的版本已经支持了使用纯黑作为黑色主题背景色。
