### ISSUE TITLE
请问能否添加对docker容器名互联的支持

### ISSUE THREAD

**Issue by tecsar9000** [haishanh/yacd#697]
目前我用docker compose安装的clash和yacd，同compose里很多容器都是可以直接用容器名直接连接的，这个好像不行，请问能否添加一下容器名连接的支持，这样设置好环境变量以后再也不用进界面输ip和端口了

**Comment by haishanh** [comment]
这个做不到，yacd docker image 也只是包含了静态文件，yacd 是个纯前端的运行在用户的浏览器中的应用。用户浏览器并没有 docker 内部的 dns 或 link 的 context，没法解析容器名。
