### ISSUE TITLE
点了个连接选项，提示错误：oops, something went wrong!

### ISSUE THREAD

**Issue by Wxiaosong** [haishanh/yacd#698]
![image](https://user-images.githubusercontent.com/31926069/169664387-97856c67-83b2-4d81-b344-d06486e03db2.png)

请问遇到这个问题怎么解决呢，重新建立容器好像没用

**Comment by JohyC** [comment]
同样问题。。。等待解决

**Comment by Arbsd** [comment]
同，我是除了概览能看点哪都错误

**Comment by AoEiuV020** [comment]
我也遇到这个，但刷新一下就恢复正常了，再也没出现，

**Comment by Arbsd** [comment]
> 我也遇到这个，但刷新一下就恢复正常了，再也没出现，

谢谢，我刚刚也找到这个原因了，就是固件控制面板换了，浏览器没更新。还有普通刷新没有用，必须按ctrl+F5强制刷新

**Comment by haishanh** [comment]
（可能还是 service worker 我实现的有问题。）

以后遇到这种问题，可以打开浏览器开发工具，清空 storage 应该就可以解决。
另外也可以把开发工具 console 显示的错误反馈给我。
