### ISSUE TITLE
测速没反应，请求状态“（已屏蔽：其他）”

### ISSUE THREAD

**Issue by AoEiuV020** [haishanh/yacd#699]
![image](https://user-images.githubusercontent.com/11682198/169738597-82be88d4-e0b5-4319-801e-806c7fa07c7b.png)

隔壁clash.razord.top正常，

Chrome 已是最新版本
版本 101.0.4951.67（正式版本） （64 位）

**Comment by AoEiuV020** [comment]
是被广告拦截插件禁止的，
ublock origin, EasyPrivacy规则里的/generate_204
搞不懂他们在想什么，居然无脑封禁204，

**Comment by MakiseKurisu** [comment]
别把issue关了啊……还可以讨论一下是不是需要更换测试用的url

**Comment by AoEiuV020** [comment]
@MakiseKurisu 也有道理，

EasyPrivacy规则想禁止的是，
http://www.gstatic.com/generate_204

而我们的测速请求是
http://127.0.0.1:9090/proxies/%F0%9F%87%BA%F0%9F%87%B8%20A%C2%B7%E7%BE%8E%E5%9B%BD%2001/delay?timeout=5000&url=http://www.gstatic.com/generate_204

隔壁clash.razord.top请求的是，
http://127.0.0.1:9090/proxies/%F0%9F%87%A7%F0%9F%87%B7%20A%C2%B7%E5%B7%B4%E8%A5%BF%2001/delay?timeout=5000&url=http:%2F%2Fwww.gstatic.com%2Fgenerate_204

感觉算是yacd测速这里url参数没做url encode导致EasyPrivacy误伤，
希望参考隔壁，规范编码url参数，
不过同时我感觉EasyPrivacy也管得太宽了，我不打算用了，
