### ISSUE TITLE
右边被撑开时，左边侧边栏 label 会被换行，“代理”和“连接”页面都有问题

### ISSUE THREAD

**Issue by qiuxiang** [haishanh/yacd#716]
![Screenshot 2022-09-15 10 17 06](https://user-images.githubusercontent.com/1709072/190298123-f167f264-d6bb-48dd-946e-344c88fdb2cb.png)
![Screenshot 2022-09-15 10 16 59](https://user-images.githubusercontent.com/1709072/190298126-5783560b-c534-4861-a44c-fd2ab52b024b.png)

给 label 加 `white-space: nowrap;` 就可以解决，PR 也提了 https://github.com/haishanh/yacd/pull/715

**Comment by yuumimi** [comment]
你的方法，
在英文状态下正常。
在中文状态下，连接页面正常，代理页面还是会换行。

**Comment by qiuxiang** [comment]
@yuumimi 就是在中文环境下测的，`white-space: nowrap;` 怎么可能被换行呢

**Comment by yuumimi** [comment]
@qiuxiang 我是用 https://github.com/qiuxiang/yacd/tree/gh-pages 测试的，你把浏览器窗口再调小一点试试，还要测试下在移动端是否正常。

**Comment by qiuxiang** [comment]
试了，没有出现，有截图吗，我是真的很好奇 nowrap 的情况下是怎么会被换行的

**Comment by qiuxiang** [comment]
![Screenshot 2022-09-15 14 52 37](https://user-images.githubusercontent.com/1709072/190335011-04115ea2-b364-4b6d-aa72-4c191242a0bd.png)
![Screenshot 2022-09-15 14 52 09](https://user-images.githubusercontent.com/1709072/190335014-9b03b84f-9c59-4647-9f1b-633ab802307b.png)

**Comment by qiuxiang** [comment]
@yuumimi 代码已经合并了，http://yacd.haishan.me/ 就可以试

**Comment by yuumimi** [comment]
@qiuxiang 是我弄错了，以为 https://github.com/qiuxiang/yacd/tree/gh-pages 是修复后的版本。用了最新版没问题了。

**Comment by qiuxiang** [comment]
我那个仓库没有合到 pages，只是线上加一段代码，甚至没有拉到本地跑过
