### ISSUE TITLE
http://127.0.0.1:9090 Fail to connect

### ISSUE THREAD

**Issue by WandernForte** [haishanh/yacd#726]
如题，整了约6个小时没有整明白咋回事

**Comment by WandernForte** [comment]
更新：8小时没解决

**Comment by duchenpaul** [comment]
F12 怎么报错的? 浏览器访问http://127.0.0.1:9090 返回啥?

**Comment by Lycofuture** [comment]
估计是没开端口,装有宝塔面板的话，服务器防火墙开了端口后还要再去宝塔面板里面开端口才能有效

**Comment by HeroicPhoenix** [comment]
你clash配置了allow-lan: true了嘛

**Comment by WandernForte** [comment]
> 估计是没开端口,装有宝塔面板的话，服务器防火墙开了端口后还要再去宝塔面板里面开端口才能有效

是这个问题。。。
