### ISSUE TITLE
增加ipv6访问clash面板

### ISSUE THREAD

**Issue by 643406834** [haishanh/yacd#730]

**Comment by xaotag** [comment]
这个本来就可以使用ipv6访问。

**Comment by haishanh** [comment]
我理解 op 指的应该是用 docker container 的场景。目前 docker iamge 里面的 nginx 是 listen 的 `:80`， ipv6 访问应该没啥问题。

**Comment by KobeBryant-24** [comment]
> 我理解 op 指的应该是用 docker container 的场景。目前 docker iamge 里面的 nginx 是 listen 的 `:80`， ipv6 访问应该没啥问题。

有问题哦，容器里ipv6被禁用了，ping不通v6地址，内网访问v4没问题，v6打不开。

```
/ # sysctl -a | grep disable_ipv6
sysctl: error reading key 'net.ipv6.conf.all.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.default.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.eth0.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.lo.stable_secret': I/O error
sysctl: error reading key 'net.ipv6.conf.sit0.stable_secret': I/O error
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.sit0.disable_ipv6 = 1
```

**Comment by anjue39** [comment]
是的。我用ipv6模式也打不开

**Comment by LunaticXJ** [comment]
我docker部署桥接模式后IPV6也访问不了，可能需要改成host但是端口不知道怎么改成不是默认的80，有大佬指点一下吗

**Comment by xaotag** [comment]
> 我docker部署桥接模式后IPV6也访问不了，可能需要改成host但是端口不知道怎么改成不是默认的80，有大佬指点一下吗
第二行下面添加`  listen       [::]:80 `
![image](https://github.com/haishanh/yacd/assets/40427877/8a3df36e-dfe4-41b2-8138-d8b4cd49db5d)

**Comment by xaotag** [comment]
> 我docker部署桥接模式后IPV6也访问不了，可能需要改成host但是端口不知道怎么改成不是默认的80，有大佬指点一下吗

看错了，想用那个端口就改成啥，或者使用 -p参数指定docker的端口
