### ISSUE TITLE
面板显示错误

### ISSUE THREAD

**Issue by Lycofuture** [haishanh/yacd#734]
打开面显示Oops, something went wrong!
![cla](https://user-images.githubusercontent.com/77215384/211246995-ee71a042-60ef-4725-87d6-2c8a3deb12a3.png)

我的配置是这样的 
![edsf](https://user-images.githubusercontent.com/77215384/211247082-4fa4c08c-31d5-4c3d-b7c3-db0fd7938e4f.png)

**Comment by haishanh** [comment]
可以参考一下 https://github.com/haishanh/yacd/issues/735#issuecomment-1407698591 看能不能解决
应该是有 bug，但目前没那么多时间去找问题所在
