### ISSUE TITLE
[BUG] 启动页叉掉默认9090出现Oops, something went wrong!

### ISSUE THREAD

**Issue by cyo57** [haishanh/yacd#735]
已无法再次正常使用网站
Firefox 108.0.1

**Comment by andy0532** [comment]
这么巧，我也是一模一样的情况

**Comment by haishanh** [comment]
遇到这种情况的话，会操作的人可以打开 dev tools Console panel 截个图

**Comment by cyo57** [comment]
> 
是这个吗
![0](https://user-images.githubusercontent.com/43310694/213521935-fda62fd3-503a-45d9-841d-bacab6e16eaa.png)

**Comment by kid-oh** [comment]
尴尬了 我也遇到了
<img width="1440" alt="截屏2023-01-26 下午8 44 40" src="https://user-images.githubusercontent.com/30406467/214838799-4038f5bd-aeef-4a66-891d-3c46ca87122a.png">

**Comment by haishanh** [comment]
@kid-oh 我还不清楚 root cause 是什么，你可以考虑清除一下 local storage，Safari 上可以这样

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1166872/215338015-d7b7678f-fe9d-45bd-bb44-967ea684412c.png">

**Comment by kid-oh** [comment]
> @kid-oh 我还不清楚 root cause 是什么，你可以考虑清除一下 local storage，Safari 上可以这样
> 
> <img alt="image" width="789" src="https://user-images.githubusercontent.com/1166872/215338015-d7b7678f-fe9d-45bd-bb44-967ea684412c.png">

好的，我是直接清除cookie就好了

**Comment by cyo57** [comment]
> @kid-oh 我还不清楚 root cause 是什么，你可以考虑清除一下 local storage，Safari 上可以这样
> 
> <img alt="image" width="789" src="https://user-images.githubusercontent.com/1166872/215338015-d7b7678f-fe9d-45bd-bb44-967ea684412c.png">

firefox有效 可以用了

**Comment by HeroicPhoenix** [comment]
谷歌浏览器可以这样清除一下local storage（本地存储空间），就可以了！
<img width="658" alt="截屏2023-02-17 11 06 17" src="https://user-images.githubusercontent.com/54227820/219539938-42406f47-6d87-4729-8605-af74f8693159.png">

**Comment by piwawa** [comment]
我还是不行啊 第一次就就报opps，本地存储空间都没东西，我是通过VSCODE SSH远控服务器，服务器内运行clash docker，打开了9090的端口转发到本机，但是本机死活进不去http://localhost:9090/

**Comment by ohsc** [comment]
<img width="571" alt="image" src="https://github.com/haishanh/yacd/assets/187528/bbe836a7-bb79-412c-ba62-109d6b219a20">
清理 localstorage、cookie 都没有用。一样的报错

**Comment by sparkssssssssss** [comment]
请问作者定位到问题了吗?
我手机via打开就这样,也没法调试

**Comment by hapesundog** [comment]
![image](https://github.com/haishanh/yacd/assets/47639764/495f19fd-3e3f-47b4-9bbd-29529ebccfe8)
chrome浏览器有效

**Comment by hapesundog** [comment]
![image](https://github.com/haishanh/yacd/assets/47639764/e159df7f-823f-4cbc-b8f0-d33102e56534)
chrome浏览器有效
