### ISSUE TITLE
搭配P核20230129 ARM64无限重载

### ISSUE THREAD

**Issue by Rakau** [haishanh/yacd#740]
RT，访问面板后，面板表现为无限刷新操作

**Comment by Rakau** [comment]
已解决

**Comment by Henry-ZHR** [comment]
怎么解决的，我这边也这样

浏览器 Firefox 110.0b8，Clash 1.13.0，yacd 313a182a460401dcad942081a4b54bee48f17b64

**Comment by Rakau** [comment]
> 怎么解决的，我这边也这样
> 
> 浏览器 Firefox 110.0b8，Clash 1.13.0，yacd 313a182a460401dcad942081a4b54bee48f17b64

换meta的面板

**Comment by wutongskype** [comment]
我用 meta的Alpha版也是无限重载
用nginx搭静态页面页面显示空白

**Comment by wutongskype** [comment]
> > 怎么解决的，我这边也这样
> > 浏览器 Firefox 110.0b8，Clash 1.13.0，yacd [313a182](https://github.com/haishanh/yacd/commit/313a182a460401dcad942081a4b54bee48f17b64)
> 
> 换meta的面板

我用 meta的Alpha版也是无限重载
改用nginx搭静态页面页面显示空白

大佬有没有nginx静态页面搭yacd的模板呀?

**Comment by Rakau** [comment]
> > > 怎么解决的，我这边也这样
> > > 浏览器 Firefox 110.0b8，Clash 1.13.0，yacd [313a182](https://github.com/haishanh/yacd/commit/313a182a460401dcad942081a4b54bee48f17b64)
> > 
> > 
> > 换meta的面板
> 
> 我用 meta的Alpha版也是无限重载 改用nginx搭静态页面页面显示空白
> 
> 大佬有没有nginx静态页面搭yacd的模板呀?

无，我换了之后清了下缓存就正常了
