### ISSUE TITLE
index.html无法打开

### ISSUE THREAD

**Issue by HWE-Yoko** [haishanh/yacd#747]
环境：
系统：Windows 10 专业版 22H2
浏览器：MicroSoft EDGE 版本 110.0.1587.63 (正式版本) (64 位)
YACD版本：v0.3.8

下载了最新的Releases，解压并打开index.html，发现无法打开，浏览器调试模式报错如下：

![image](https://user-images.githubusercontent.com/29684758/223046583-61c2122b-efd6-4689-ae86-7e4b86ebfb97.png)

请问一下是什么问题？

**Comment by HWE-Yoko** [comment]
研究明白了，是7zip的问题，7zip解压缩之后就不能用，用Linux tar命令解压之后就正常了。

**Comment by Hanbing59** [comment]
不好意思，我也遇到同样的问题。请问你不是在windows下用么，怎么用linux tar解压呢？意思是，你先在linux下解压后，然后把解压完的包拷贝到windows下吗？ @HWE-Yoko

**Comment by HWE-Yoko** [comment]
> 

我是在Windows下使用，使用的解压软件是7zip，解压出来无法使用，但是下载到Linux下使用tar命令解压出来再传输到Windows就可以使用了。

**Comment by Hanbing59** [comment]
Thanks! 我试试
