### ISSUE TITLE
yacd emoticon 

### ISSUE THREAD

**Issue by volatilaq** [haishanh/yacd#749]
I want to ask, why when I open Yacd on Opera, no emoticons appear
but when I open Yacd on Firefox, emoticons appear.
I also tried opening yacd in chrome, and it's the same with opera, emoticons don't appear,
why browser chrome and opera cant read emoticons like in firefox?
do you have a solution?

![yacd-chrome](https://user-images.githubusercontent.com/122660998/224924519-9b392a0a-7921-4953-9127-bdd1c62ec65b.PNG)
![yacd-firefox](https://user-images.githubusercontent.com/122660998/224924525-5f845c03-c64a-4b04-a8ff-301216858adf.PNG)
![yacd-opera](https://user-images.githubusercontent.com/122660998/224924530-a11663a6-1405-4f54-b07f-32f3efe39e9b.PNG)

**Comment by haishanh** [comment]
I think it's related to the font family use in yacd. I thought "Segoe UI Emoji" is what Windows used to render Emoji. It's included in the CSS, not sure why it's not working in Chrome and Opera. 

https://github.com/haishanh/yacd/blob/0b254f1c8784ef47e290329ef0339a602af4aa4d/src/components/Root.scss#L57

I don't have a Windows machine, if you have some web development experience you may try appending some additional font family like below and see if it works.

```
apple color emoji, segoe ui emoji, noto color emoji, android emoji, emojisymbols, emojione mozilla, twemoji mozilla, segoe ui symbol
```

**Comment by volatilaq** [comment]
> I think it's related to the font family use in yacd. I thought "Segoe UI Emoji" is what Windows used to render Emoji. It's included in the CSS, not sure why it's not working in Chrome and Opera.
> 
> https://github.com/haishanh/yacd/blob/0b254f1c8784ef47e290329ef0339a602af4aa4d/src/components/Root.scss#L57
> 
> I don't have a Windows machine, if you have some web development experience you may try appending some additional font family like below and see if it works.
> 
> ```
> apple color emoji, segoe ui emoji, noto color emoji, android emoji, emojisymbols, emojione mozilla, twemoji mozilla, segoe ui symbol
> ```

how to apply the code above? sorry I don't understand in css code
