### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by tianjiaoshanzai** [haishanh/yacd#750]
已经按照一些issue的意见关闭了该选项
![image](https://user-images.githubusercontent.com/38492739/225025151-1aca16a0-5295-49e8-ab3e-66295c53ffb0.png)

但是还是Failed to connect 
![image](https://user-images.githubusercontent.com/38492739/225025894-48440691-b62c-482d-90aa-68b0416bf3f1.png)

![image](https://user-images.githubusercontent.com/38492739/225025535-4e871b10-2960-46d0-bc00-3912e4431e1e.png)

**Comment by piwawa** [comment]
我也是 就是进去了 也连接不上

**Comment by peter-thenardier** [comment]
ubuntu 22.04LTS  同样的问题

**Comment by tianjiaoshanzai** [comment]
我明白了，原来webui的使用环境需要能访问到目标ip,我在外网使用，端口没开放，而且一直在使用内网ip,以为是转发到内网，ui不处理网络。

通过端口开放并使用外网ip可以解决

**Comment by lujiaweicy** [comment]
把 external-controller: 改成 ‘0.0.0.0:9090’
