### ISSUE TITLE
一直不停的刷新

### ISSUE THREAD

**Issue by nasaboy** [haishanh/yacd#751]
之前也按照这种方法配置的，用chrome或者edge都不会一直刷新，可以正常使用，现在出现一直刷新页面，无法正常使用，F12里面的出现这个错误，不知道如何解决
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
external-ui: C:/Users/****/Downloads/yacd-gh-pages

![微信截图_20230315144947](https://user-images.githubusercontent.com/5997682/225229336-0b883fc0-ab82-491d-bd08-847836ea9aab.png)

**Comment by everyx** [comment]
挂在 sing-box 下，也碰到了这个问题，访问的路径是 `http://127.0.0.1:9090/ui/`，但是请求的 `sw.js` 是 `http://127.0.0.1:9090/sw.js` 就 404 了，不知道是不是这个原因导致的，正确的路径应该是 `http://127.0.0.1:9090/ui/sw.js`

**Comment by kuaizi** [comment]
建议更新一下https://github.com/haishanh/yacd/tree/gh-pages

**Comment by nasaboy** [comment]
暂时用这个了 https://yacd-haishan.vercel.app

**Comment by daiaji** [comment]
> 暂时用这个了 https://yacd-haishan.vercel.app 可以的话，更新一下楼上说的，就自己部署在本地了

可用，gh-pages分支确实要更新了。
蛮多教程都是用的这个分支直接clone下来。

**Comment by haishanh** [comment]
gh-pages 更新了
