### ISSUE TITLE
如何使用未发布的新版

### ISSUE THREAD

**Issue by debiansid** [haishanh/yacd#754]
目前一直使用release的zip,有什么办法使用git里面的最新的版本

**Comment by everyx** [comment]
> 目前一直使用release的zip,有什么办法使用git里面的最新的版本

Archlinux 用户可以使用我维护的 AUR 包 [yacd-git](https://aur.archlinux.org/packages/yacd-git) 和 [yacd-ghp-bin](https://aur.archlinux.org/packages/yacd-ghp-bin)（基于 gh-pages 分支，就不用每次本地编译了）

**Comment by debiansid** [comment]
用的debian11

**Comment by debiansid** [comment]
谢谢指点
