### ISSUE TITLE
关于延迟测速 URL

### ISSUE THREAD

**Issue by labulac** [haishanh/yacd#762]
yacd 的配置里面有个延迟测速url，clash配置里面有个自动测速，也会有个url，这两个测速到底以哪个为准呢大佬？

**Comment by rsgdn** [comment]
+1 我也想知道

**Comment by lhbdhr** [comment]
yacd config页面的测速url是用来修改clash客户端配置的。
测速是用的clash客户端配置的url。

但是按理说你改了yacd里的测速url，客户端的测速url会改成你网页设置的url。
但是我没有测试过管不管用。按理说逻辑上应该是这样。
