### ISSUE TITLE
sw.js 访问404问题; nginx prefix location路径

### ISSUE THREAD

**Issue by echoface** [haishanh/yacd#768]
在使用nginx 通过prefix location 指向站点时, 报错访问有报错 sw.js 404( 原因是没有路径的prefix)

```
...
     location /yacd/ {
                
                alias /var/www/yacd/;

                autoindex on;
                autoindex_localtime on;
                autoindex_exact_size off;
                proxy_set_header X-Real-IP $remote_addr;
      }
....
```

**Comment by iwestlin** [comment]
我也遇到了……
实际上这个问题已经修复了：https://github.com/haishanh/yacd/pull/753
但是readme给出的下载链接`https://github.com/haishanh/yacd/archive/gh-pages.zip` 是gh-pages分支的，那个分支并没有更新修复代码……

其实只需要改一个地方：把 `index-3e6aad90.js` 里的 `const n="/sw.js"`  改成 `const n="./sw.js"` 就好了

<img width="905" alt="截屏2023-05-13 上午12 03 21" src="https://github.com/haishanh/yacd/assets/6235509/d4131ca9-5efd-4141-80f1-de8b206e4a18">

**Comment by echoface** [comment]
great job，thanks，
