### ISSUE TITLE
浏览器无法访问本地webui界面

### ISSUE THREAD

**Issue by Pr0pHesyer** [haishanh/yacd#783]
windows11

clash  pre 2023.6.30
clash配置文件
`external-controller: 127.0.0.1:9090
external-ui: 'C:\Other\SoftWare\MySoftWare\clash\yacd'
secret: 'gsvrfxbgtgfb'`

yacd 0.3.8

![image](https://github.com/haishanh/yacd/assets/74277431/ee9d5827-c78b-4262-8b36-d2abaed10383)

chrome 114 白屏
![image](https://github.com/haishanh/yacd/assets/74277431/347b7219-aa0b-4db4-828c-559c33cf78c2)

firefox 115 点击Add控制台无输出
![image](https://github.com/haishanh/yacd/assets/74277431/aca23466-e0d9-412d-a8ba-bfbc4eaac4b0)

edge 114 白屏
![image](https://github.com/haishanh/yacd/assets/74277431/0d8e4b6b-096e-43bc-872c-80dae3a6c5a8)

[clash.razord.top](clash.razord.top) 可正常使用

**Comment by j10ccc** [comment]
你这两个 chromium 浏览器怎么请求根目录请求的是 `tsx`？
