### ISSUE TITLE
进入 web 界面 显示这个  一直报错

### ISSUE THREAD

**Issue by FlyumMicro** [haishanh/yacd#788]
![image](https://github.com/haishanh/yacd/assets/50798769/9780fb4d-d788-4cf1-868b-bb100a36338d)
请问大佬们 这个界面怎么配置没懂

**Comment by doubly-yi** [comment]
将你配置的链接和地址密钥都填进去就好了
![image](https://github.com/haishanh/yacd/assets/26616417/a9854ec8-47e3-47ba-ad2d-95c104eff27a)

**Comment by woshichenghaibo** [comment]
> 将你配置的链接和地址密钥都填进去就好了 ![image](https://user-images.githubusercontent.com/26616417/261958100-a9854ec8-47e3-47ba-ad2d-95c104eff27a.png)

wo和楼主一样的问题，停在登陆界面就是进不去

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'

没有填写配置密码
