### ISSUE TITLE
进入web页面报错:Oops, something went wrong!

### ISSUE THREAD

**Issue by C-Rosemary** [haishanh/yacd#797]
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: start worker process 12
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: start worker process 11
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: start worker process 10
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: start worker process 9
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: start worker processes
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: OS: Linux 4.4.302+
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219)
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: nginx/1.23.2
2023/09/18 18:04:47 | stdout | 2023/09/18 10:04:47 [notice] 8#8: using the "epoll" event method

![Snipaste_2023-09-18_18-05-07](https://github.com/haishanh/yacd/assets/30623152/0ebd9c9d-284b-4997-a196-0e23dd372665)
![Snipaste_2023-09-18_18-07-41](https://github.com/haishanh/yacd/assets/30623152/1c0912ec-5793-4050-871f-0929a478c1b5)

**Comment by C-Rosemary** [comment]
重新配置成其他端口就进去了，怪欸

**Comment by clarkchen900** [comment]
> 重新配置成其他端口就进去了，怪欸

解决了我的问题，谢
