### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by yangrq1018** [haishanh/yacd#813]
Run `npm start` gives error

[plugin:vite:import-analysis] Missing "./dist/TwemojiCountryFlags.woff2" specifier in "country-flag-emoji-polyfill" package

It seems `country-flag-emoji-polyfill` package.json has a section which makes vite unhappy

```
  "exports": {
    "require": "./dist/index.cjs",
    "default": "./dist/index.modern.js"
  },
```
comment this part and problem is gone.

**Comment by hinak0** [comment]
use pnpm instead.

**Comment by yangrq1018** [comment]
It works, thanks.
