### ISSUE TITLE
[已解决]端口能正常访问,但无法登录

### ISSUE THREAD

**Issue by aur0aur** [haishanh/yacd#816]
port: 9870
socks-port: 9871
allow-lan: false
mode: Rule
log-level: info
external-controller: 0.0.0.0:11111
secret: ''
![Snipaste_2024-01-15_18-28-38](https://github.com/haishanh/yacd/assets/150316889/0cadc9dd-3d8d-4d24-878d-890cedf67e4e)
![Snipaste_2024-01-15_18-31-15](https://github.com/haishanh/yacd/assets/150316889/97adceeb-140b-4120-8ba4-d0dacafdc7af)
![Snipaste_2024-01-15_18-32-16](https://github.com/haishanh/yacd/assets/150316889/b1bb233c-d2f3-4b51-9b69-08308210d2dc)

**Comment by Bssn520** [comment]
一样的问题，请问您解决了吗？

**Comment by eli-yip** [comment]
建议检查一下面板是否使用了HTTPS，大部分浏览器禁止从HTTPS界面请求HTTP（Clash）。

很多浏览器都会默认将HTTP跳转到HTTPS，得将面板加入白名单。

**Comment by rvnox** [comment]
Unauthorized 报错 。。。

**Comment by aur0aur** [comment]
> 建议检查一下面板是否使用了HTTPS，大部分浏览器禁止从HTTPS界面请求HTTP（Clash）。
> 
> 很多浏览器都会默认将HTTP跳转到HTTPS，得将面板加入白名单。

![Snipaste_2024-02-04_10-00-54](https://github.com/haishanh/yacd/assets/150316889/ea158220-2054-47c5-93c1-71b621d92e4f)
http请求本地可以连通,但是请求服务器不行,尝试过chrome设置yacd关闭HSTS没效果.
还有其他方式将面板添加白名单吗?

**Comment by aur0aur** [comment]
> 建议检查一下面板是否使用了HTTPS，大部分浏览器禁止从HTTPS界面请求HTTP（Clash）。
> 
> 很多浏览器都会默认将HTTP跳转到HTTPS，得将面板加入白名单。

![Snipaste_2024-02-04_10-07-03](https://github.com/haishanh/yacd/assets/150316889/9ac45e79-f1bf-433d-ae8c-0f078d788d94)
http请求本地可以连通,但是请求服务器不行,chrome设置yacd关闭HSTS无法关闭yacd页面的https
还有其他方式将面板添加白名单吗?

**Comment by aur0aur** [comment]
已解决,将chrome对yacd.haishan.me的不安全内容改为允许即可
![Snipaste_2024-02-04_11-19-26](https://github.com/haishanh/yacd/assets/150316889/e320f8af-93c8-4c88-bc03-59585063a854)

**Comment by aur0aur** [comment]
> 建议检查一下面板是否使用了HTTPS，大部分浏览器禁止从HTTPS界面请求HTTP（Clash）。
> 
> 很多浏览器都会默认将HTTP跳转到HTTPS，得将面板加入白名单。

thanks

**Comment by Fau818** [comment]
> 已解决,将chrome对yacd.haishan.me的不安全内容改为允许即可 ![Snipaste_2024-02-04_11-19-26](https://private-user-images.githubusercontent.com/150316889/302074780-e320f8af-93c8-4c88-bc03-59585063a854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg4NDksIm5iZiI6MTcxMzI0ODU0OSwicGF0aCI6Ii8xNTAzMTY4ODkvMzAyMDc0NzgwLWUzMjBmOGFmLTkzYzgtNGM4OC1iYzAzLTU5NTg1MDYzYTg1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmEwNmNmYjg3YjYyOGRlNzQ4ZDY2M2E1MGM5NGVhZWRhZjViODgzOWVkZjBkOGQ5NTEyYzM0ZjYxNWJjOGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PGnXXC5LwqXVKOGdk9t-WhFXm_nwp_x5Wc5en4_OESY)

好解决方案! 赞赞赞赞赞!

**Comment by tp20c5** [comment]
也可以整体改造为https连接，注意做好ws透传就行

**Comment by xxx-x-x** [comment]
依旧没用

<img width="2560" height="1279" alt="Image" src="https://github.com/user-attachments/assets/edb72ff4-3722-4b68-aa68-bf32712ec673" />
